/**
 * src/lib/cv/builder.ts
 *
 * Pure CV data-model + builder. Given a fully-loaded provider snapshot from
 * Prisma, return a typed `Cv` object that any of the renderers (text /
 * markdown / PDF) can consume. Splitting it this way means:
 *
 *   - the renderers are dumb formatters (easy to unit test in isolation),
 *   - the snapshot loader is the only file that knows about Prisma
 *     (`CmeService.loadCvSnapshot`),
 *   - the builder itself is a pure function with deterministic output for
 *     any given snapshot, so a single test fixture covers every renderer
 *     contract.
 *
 * Wave 3.2 (CVO platform): the auto-CV is core CVO deliverable evidence
 * for NCQA CR-2 (work history) + CR-4 (education) + JC OPPE indicator
 * tracking.
 */

export interface CvSnapshotProvider {
  legalFirstName: string | null;
  legalMiddleName: string | null;
  legalLastName: string | null;
  npi: string | null;
  providerType: { name: string; abbreviation: string } | null;
  profile: {
    personalEmail: string | null;
    mobilePhone: string | null;
    medicalSchoolName: string | null;
    medicalSchoolCountry: string | null;
    graduationYear: number | null;
    specialtyPrimary: string | null;
    specialtySecondary: string | null;
    ecfmgNumber: string | null;
  } | null;
}

export interface CvSnapshotLicense {
  state: string;
  licenseType: string;
  licenseNumber: string;
  status: string;
  expirationDate: Date | null;
  isPrimary: boolean;
}

export interface CvSnapshotBoardCertification {
  credentialType: string;
  status: string;
  verifiedDate: Date;
  expirationDate: Date | null;
}

export interface CvSnapshotPrivilege {
  facilityName: string;
  privilegeType: string;
  status: string;
  effectiveDate: Date | null;
  expirationDate: Date | null;
}

export interface CvSnapshotWorkHistory {
  employerName: string;
  position: string | null;
  startDate: Date | null;
  endDate: Date | null;
}

export interface CvSnapshotCmeCredit {
  activityName: string;
  category: string;
  credits: number;
  completedDate: Date;
}

export interface CvSnapshot {
  provider: CvSnapshotProvider;
  licenses: CvSnapshotLicense[];
  boardCertifications: CvSnapshotBoardCertification[];
  privileges: CvSnapshotPrivilege[];
  workHistory: CvSnapshotWorkHistory[];
  cmeCredits: CvSnapshotCmeCredit[];
}

// ─── Output model ────────────────────────────────────────────────────────────

export interface CvHeader {
  fullName: string;
  npi: string | null;
  providerTypeLabel: string | null;
  email: string | null;
  phone: string | null;
}

export interface CvSection {
  title: string;
  entries: CvEntry[];
  /** Optional summary line shown at the bottom of the section. */
  summary?: string;
}

export interface CvEntry {
  /** Bold/primary line. */
  primary: string;
  /** Greyed-out line under primary, e.g. dates. */
  secondary?: string | null;
  /** Inline metadata badges (e.g. "Active", "Primary"). */
  badges?: string[];
}

export interface Cv {
  header: CvHeader;
  sections: CvSection[];
  /** ISO timestamp the CV was generated. */
  generatedAtIso: string;
  /**
   * Branding line printed in the footer of every export. Lets the CVO
   * platform identify itself on the document chain of custody.
   */
  footerBrand: string;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

const FOOTER_BRAND_DEFAULT =
  "Generated by ESSEN Credentialing — CVO Platform";

function fmtDate(d: Date | null | undefined): string {
  if (!d) return "—";
  return d.toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

function fmtDateOrPresent(d: Date | null | undefined): string {
  return d ? fmtDate(d) : "Present";
}

function fullName(provider: CvSnapshotProvider): string {
  const parts = [
    provider.legalFirstName,
    provider.legalMiddleName,
    provider.legalLastName,
  ].filter((s): s is string => !!s && s.trim().length > 0);
  return parts.length > 0 ? parts.join(" ") : "Unknown Provider";
}

// ─── Builder ─────────────────────────────────────────────────────────────────

export interface BuildCvOptions {
  /** Override the deterministic generation timestamp (test fixtures). */
  now?: Date;
  /** Override the footer brand line (white-label customers). */
  footerBrand?: string;
}

/**
 * Build a structured CV from a provider snapshot. Pure function — no IO,
 * no Prisma client, no `Date.now()` reads when `options.now` is supplied.
 */
export function buildCv(snapshot: CvSnapshot, options: BuildCvOptions = {}): Cv {
  const now = options.now ?? new Date();
  const provider = snapshot.provider;

  const header: CvHeader = {
    fullName: fullName(provider),
    npi: provider.npi ?? null,
    providerTypeLabel: provider.providerType
      ? `${provider.providerType.name} (${provider.providerType.abbreviation})`
      : null,
    email: provider.profile?.personalEmail ?? null,
    phone: provider.profile?.mobilePhone ?? null,
  };

  const sections: CvSection[] = [];

  // ─── Education ──────────────────────────────────────────────────────────
  const eduEntries: CvEntry[] = [];
  if (provider.profile?.medicalSchoolName) {
    const country = provider.profile.medicalSchoolCountry
      ? ` (${provider.profile.medicalSchoolCountry})`
      : "";
    eduEntries.push({
      primary: `${provider.profile.medicalSchoolName}${country}`,
      secondary: provider.profile.graduationYear
        ? `Graduated ${provider.profile.graduationYear}`
        : "Graduation year not on file",
    });
  }
  if (provider.profile?.specialtyPrimary) {
    eduEntries.push({
      primary: `Primary specialty: ${provider.profile.specialtyPrimary}`,
    });
  }
  if (provider.profile?.specialtySecondary) {
    eduEntries.push({
      primary: `Secondary specialty: ${provider.profile.specialtySecondary}`,
    });
  }
  if (provider.profile?.ecfmgNumber) {
    eduEntries.push({
      primary: `ECFMG #${provider.profile.ecfmgNumber}`,
    });
  }
  sections.push({
    title: "Education",
    entries: eduEntries.length
      ? eduEntries
      : [{ primary: "No education on file." }],
  });

  // ─── Licenses ───────────────────────────────────────────────────────────
  const licenseEntries: CvEntry[] = snapshot.licenses.map((lic) => {
    const badges: string[] = [];
    if (lic.isPrimary) badges.push("Primary");
    badges.push(lic.status);
    return {
      primary: `${lic.state} ${lic.licenseType} #${lic.licenseNumber}`,
      secondary: lic.expirationDate
        ? `Expires ${fmtDate(lic.expirationDate)}`
        : "No expiration on file",
      badges,
    };
  });
  sections.push({
    title: "Licenses",
    entries: licenseEntries.length
      ? licenseEntries
      : [{ primary: "No licenses on file." }],
  });

  // ─── Board certifications ───────────────────────────────────────────────
  const boardEntries: CvEntry[] = snapshot.boardCertifications.map((b) => ({
    primary: b.credentialType.replace(/^BOARD_/, ""),
    secondary: `Verified ${fmtDate(b.verifiedDate)}${
      b.expirationDate ? ` · Expires ${fmtDate(b.expirationDate)}` : ""
    }`,
    badges: [b.status],
  }));
  sections.push({
    title: "Board certifications",
    entries: boardEntries.length
      ? boardEntries
      : [{ primary: "No board certifications on file." }],
  });

  // ─── Hospital privileges ────────────────────────────────────────────────
  const privEntries: CvEntry[] = snapshot.privileges.map((hp) => {
    const dates: string[] = [];
    if (hp.effectiveDate) dates.push(`Effective ${fmtDate(hp.effectiveDate)}`);
    if (hp.expirationDate) dates.push(`Expires ${fmtDate(hp.expirationDate)}`);
    return {
      primary: `${hp.facilityName} — ${hp.privilegeType}`,
      secondary: dates.length ? dates.join(" · ") : null,
      badges: [hp.status],
    };
  });
  sections.push({
    title: "Hospital privileges",
    entries: privEntries.length
      ? privEntries
      : [{ primary: "No hospital privileges on file." }],
  });

  // ─── Work history ───────────────────────────────────────────────────────
  const workEntries: CvEntry[] = snapshot.workHistory.map((wh) => ({
    primary: wh.position ? `${wh.employerName} — ${wh.position}` : wh.employerName,
    secondary: `${fmtDate(wh.startDate)} – ${fmtDateOrPresent(wh.endDate)}`,
  }));
  sections.push({
    title: "Work history",
    entries: workEntries.length
      ? workEntries
      : [{ primary: "No work history on file." }],
  });

  // ─── CME credits ────────────────────────────────────────────────────────
  const cmeEntries: CvEntry[] = snapshot.cmeCredits.map((c) => ({
    primary: c.activityName,
    secondary: `${fmtDate(c.completedDate)} · ${c.category} · ${c.credits} credit${
      c.credits === 1 ? "" : "s"
    }`,
  }));
  const cmeTotal = snapshot.cmeCredits.reduce((sum, c) => sum + c.credits, 0);
  sections.push({
    title: "CME credits",
    entries: cmeEntries.length
      ? cmeEntries
      : [{ primary: "No CME credits on file." }],
    summary: cmeEntries.length
      ? `Total CME credits on file: ${cmeTotal}`
      : undefined,
  });

  return {
    header,
    sections,
    generatedAtIso: now.toISOString(),
    footerBrand: options.footerBrand ?? FOOTER_BRAND_DEFAULT,
  };
}
