/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API key + environment health probe
         * @description Verifies that the supplied API key is active and that the
         *     environment is reachable. Returns the keyId so the caller can
         *     confirm which key is in use without echoing the secret, the
         *     API surface version, and a server-side timestamp for
         *     clock-skew checks.
         *
         *     Authentication: ANY active API key. Unlike every other v1
         *     operation, this endpoint does NOT require a specific scope
         *     — a brand-new, scopeless key returns 200 here. This makes
         *     it the natural first call when wiring up the SDK.
         *
         *     Versioning: shipped in v1.1.0 (SemVer minor — additive
         *     only). See `docs/api/versioning.md`.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List providers
         * @description Returns a paginated list of providers. Supports filtering by
         *     `status` and `npi`. PHI is never included.
         */
        get: operations["listProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one provider (full envelope, no PHI) */
        get: operations["getProvider"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{id}/cv.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a provider's CV as PDF
         * @description Streams a fully-formed Curriculum Vitae as `application/pdf`.
         *     Requires the `providers:cv` scope. The CV includes only data
         *     commonly published in CVs (name, NPI, provider type, education,
         *     licensure, board certs, hospital privileges, work history,
         *     CME log) — never SSN, DOB, DEA, or personal addresses.
         */
        get: operations["getProviderCv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sanctions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sanctions checks */
        get: operations["listSanctions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payer enrollments */
        get: operations["listEnrollments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Canonical v1 error envelope. The body of every non-2xx response
         *     from `/api/v1/*` follows this shape. Clients (including the
         *     in-tree TypeScript SDK) parse `error.code` and `error.message`.
         */
        Error: {
            error: {
                /**
                 * @description Stable machine-readable identifier for the failure
                 *     mode. Snake_case. Part of the contract — never renamed
                 *     without bumping `info.version` and following the
                 *     deprecation policy in `docs/api/versioning.md`.
                 * @example not_found
                 */
                code: string;
                /**
                 * @description Human-readable explanation, may change between releases.
                 * @example Provider not found
                 */
                message: string;
                /**
                 * @description Present on `insufficient_scope` errors — names the
                 *     scope the API key would have needed. Optional on
                 *     other errors.
                 */
                required?: string;
            };
        };
        /**
         * @description Body of a `429 Too Many Requests` response. Extends `Error`
         *     with a `retryAfterSeconds` field that mirrors the
         *     `Retry-After` header so SDKs that don't read response headers
         *     can still back off correctly.
         */
        RateLimitProblem: {
            error: {
                /**
                 * @example rate_limited
                 * @constant
                 */
                code: "rate_limited";
                /** @example Rate limit of 120 requests/min exceeded. Retry in 7s. */
                message: string;
                /**
                 * @description Seconds until the next request is allowed. Always
                 *     matches the `Retry-After` header.
                 * @example 7
                 */
                retryAfterSeconds: number;
            };
        };
        Pagination: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
        };
        /**
         * @description Result of `GET /api/v1/health`. Confirms the supplied API key
         *     is active and the environment is reachable. Never includes
         *     PHI or customer-specific business data beyond the keyId
         *     fingerprint.
         */
        Health: {
            /**
             * @description Always `true` on a 200 response. Reserved for forward-compat.
             * @example true
             */
            ok: boolean;
            /**
             * Format: cuid
             * @description Identifier of the active API key (NOT the secret).
             * @example ck0jm0a4e0000abcd1234efgh
             */
            keyId: string;
            /**
             * @description Semver version of the v1 surface (matches `info.version`).
             * @example 1.3.0
             */
            apiVersion: string;
            /**
             * Format: date-time
             * @description Server-side ISO-8601 UTC timestamp for clock-skew checks.
             * @example 2026-04-18T20:45:00.000Z
             */
            time: string;
        };
        /**
         * @description Lifecycle stage of the provider record.
         * @enum {string}
         */
        ProviderStatus: "INVITED" | "APPLICATION_IN_PROGRESS" | "VERIFICATION_IN_PROGRESS" | "COMMITTEE_REVIEW" | "APPROVED" | "DENIED" | "TERMINATED" | "SUSPENDED";
        /** @enum {string} */
        SanctionsResult: "CLEAR" | "MATCH" | "REVIEW_REQUIRED";
        /** @enum {string} */
        EnrollmentStatus: "NOT_STARTED" | "IN_PROGRESS" | "SUBMITTED" | "APPROVED" | "DENIED" | "TERMINATED";
        ProviderType: {
            name?: string;
            abbreviation?: string;
        };
        ProviderSummary: {
            /** Format: cuid */
            id: string;
            legalFirstName: string;
            legalLastName: string;
            npi?: string | null;
            status: components["schemas"]["ProviderStatus"];
            providerType?: components["schemas"]["ProviderType"];
            /** Format: date-time */
            approvedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ProviderDetail: components["schemas"]["ProviderSummary"] & {
            legalMiddleName?: string | null;
            caqhId?: string | null;
            /** Format: date-time */
            updatedAt?: string;
            profile?: {
                specialtyPrimary?: string | null;
                facilityAssignment?: string | null;
                jobTitle?: string | null;
            } | null;
            licenses?: {
                /** Format: cuid */
                id?: string;
                state?: string;
                licenseType?: string;
                status?: string;
                /** Format: date */
                expirationDate?: string | null;
            }[];
            enrollments?: {
                /** Format: cuid */
                id?: string;
                payerName?: string;
                status?: components["schemas"]["EnrollmentStatus"];
                /** Format: date */
                effectiveDate?: string | null;
            }[];
            expirables?: {
                /** Format: cuid */
                id?: string;
                expirableType?: string;
                status?: string;
                /** Format: date */
                expirationDate?: string | null;
            }[];
        };
        ProvidersPage: {
            data: components["schemas"]["ProviderSummary"][];
            pagination: components["schemas"]["Pagination"];
        };
        SanctionsCheck: {
            /** Format: cuid */
            id: string;
            /** @example OIG_LEIE */
            source: string;
            result: components["schemas"]["SanctionsResult"];
            /** Format: date-time */
            runDate: string;
            triggeredBy?: string | null;
            provider?: {
                /** Format: cuid */
                id?: string;
                legalFirstName?: string;
                legalLastName?: string;
                npi?: string | null;
            };
        };
        SanctionsPage: {
            data: components["schemas"]["SanctionsCheck"][];
            pagination: components["schemas"]["Pagination"];
        };
        Enrollment: {
            /** Format: cuid */
            id: string;
            payerName: string;
            enrollmentType?: string | null;
            status: components["schemas"]["EnrollmentStatus"];
            /** Format: date */
            effectiveDate?: string | null;
            /** Format: date-time */
            submittedAt?: string | null;
            provider?: {
                /** Format: cuid */
                id?: string;
                legalFirstName?: string;
                legalLastName?: string;
                npi?: string | null;
            };
        };
        EnrollmentsPage: {
            data: components["schemas"]["Enrollment"][];
            pagination: components["schemas"]["Pagination"];
        };
    };
    responses: {
        /** @description Missing or invalid API key. */
        Unauthorized: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description API key valid but lacks the required scope. */
        Forbidden: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Too many requests for this key. The body is a
         *     `RateLimitProblem`. The `Retry-After` header (seconds) tells
         *     you when the next request is allowed; the standard
         *     `X-RateLimit-*` headers (also present on every successful
         *     response since v1.2.0) describe your budget.
         */
        RateLimited: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RateLimitProblem"];
            };
        };
    };
    parameters: {
        /**
         * @description Optional caller-supplied correlation id. If supplied and it
         *     matches `^[A-Za-z0-9_\-]{8,128}$` the server honours it and
         *     echoes it back on the response. Otherwise the server
         *     generates one. Pair this with your client-side log lines for
         *     end-to-end tracing. Available since v1.3.0.
         */
        RequestIdHeader: string;
        /** @description 1-based page index. Default 1. */
        Page: number;
        /** @description Items per page (max 100). Default 25. */
        Limit: number;
    };
    requestBodies: never;
    headers: {
        /**
         * @description Correlation id for this request/response pair. If the inbound
         *     request supplied a valid `X-Request-Id` we honour it;
         *     otherwise we generate one server-side as `req_<hex>`.
         *     Present on every response (2xx and non-2xx). Format:
         *     `^[A-Za-z0-9_\-]{8,128}$`. Pass it to support to look up the
         *     full audit + log trail in O(1). Available since v1.3.0.
         */
        RequestId: string;
        /**
         * @description Maximum requests allowed in the current fixed window for the
         *     authenticated API key. Stable across the window. Present on
         *     every successful 2xx response and on the 429 rejection.
         */
        RateLimitLimit: number;
        /**
         * @description Requests still available in the current window (>= 0).
         *     Decrements on every accepted request. On a 429 this is `0`.
         */
        RateLimitRemaining: number;
        /**
         * @description Unix-seconds (UTC) timestamp when the current window resets
         *     and `X-RateLimit-Remaining` returns to `X-RateLimit-Limit`.
         */
        RateLimitReset: number;
        /**
         * @description Seconds the client should wait before retrying. Always >= 1.
         *     Present only on `429` responses.
         */
        RetryAfter: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Optional caller-supplied correlation id. If supplied and it
                 *     matches `^[A-Za-z0-9_\-]{8,128}$` the server honours it and
                 *     echoes it back on the response. Otherwise the server
                 *     generates one. Pair this with your client-side log lines for
                 *     end-to-end tracing. Available since v1.3.0.
                 */
                "X-Request-Id"?: components["parameters"]["RequestIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Missing, invalid, expired, or revoked API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    listProviders: {
        parameters: {
            query?: {
                /** @description 1-based page index. Default 1. */
                page?: components["parameters"]["Page"];
                /** @description Items per page (max 100). Default 25. */
                limit?: components["parameters"]["Limit"];
                status?: components["schemas"]["ProviderStatus"];
                /** @description Exact-match NPI filter. */
                npi?: string;
            };
            header?: {
                /**
                 * @description Optional caller-supplied correlation id. If supplied and it
                 *     matches `^[A-Za-z0-9_\-]{8,128}$` the server honours it and
                 *     echoes it back on the response. Otherwise the server
                 *     generates one. Pair this with your client-side log lines for
                 *     end-to-end tracing. Available since v1.3.0.
                 */
                "X-Request-Id"?: components["parameters"]["RequestIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of providers. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    getProvider: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Optional caller-supplied correlation id. If supplied and it
                 *     matches `^[A-Za-z0-9_\-]{8,128}$` the server honours it and
                 *     echoes it back on the response. Otherwise the server
                 *     generates one. Pair this with your client-side log lines for
                 *     end-to-end tracing. Available since v1.3.0.
                 */
                "X-Request-Id"?: components["parameters"]["RequestIdHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider envelope. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProviderDetail"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    getProviderCv: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Optional caller-supplied correlation id. If supplied and it
                 *     matches `^[A-Za-z0-9_\-]{8,128}$` the server honours it and
                 *     echoes it back on the response. Otherwise the server
                 *     generates one. Pair this with your client-side log lines for
                 *     end-to-end tracing. Available since v1.3.0.
                 */
                "X-Request-Id"?: components["parameters"]["RequestIdHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF CV stream. */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    "Content-Length"?: number;
                    "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    listSanctions: {
        parameters: {
            query?: {
                /** @description 1-based page index. Default 1. */
                page?: components["parameters"]["Page"];
                /** @description Items per page (max 100). Default 25. */
                limit?: components["parameters"]["Limit"];
                providerId?: string;
                result?: components["schemas"]["SanctionsResult"];
            };
            header?: {
                /**
                 * @description Optional caller-supplied correlation id. If supplied and it
                 *     matches `^[A-Za-z0-9_\-]{8,128}$` the server honours it and
                 *     echoes it back on the response. Otherwise the server
                 *     generates one. Pair this with your client-side log lines for
                 *     end-to-end tracing. Available since v1.3.0.
                 */
                "X-Request-Id"?: components["parameters"]["RequestIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of sanctions checks. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SanctionsPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    listEnrollments: {
        parameters: {
            query?: {
                /** @description 1-based page index. Default 1. */
                page?: components["parameters"]["Page"];
                /** @description Items per page (max 100). Default 25. */
                limit?: components["parameters"]["Limit"];
                status?: components["schemas"]["EnrollmentStatus"];
                /** @description Case-insensitive substring filter on payer name. */
                payer?: string;
            };
            header?: {
                /**
                 * @description Optional caller-supplied correlation id. If supplied and it
                 *     matches `^[A-Za-z0-9_\-]{8,128}$` the server honours it and
                 *     echoes it back on the response. Otherwise the server
                 *     generates one. Pair this with your client-side log lines for
                 *     end-to-end tracing. Available since v1.3.0.
                 */
                "X-Request-Id"?: components["parameters"]["RequestIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of enrollments. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentsPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
}
