/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API key + environment health probe
         * @description Verifies that the supplied API key is active and that the
         *     environment is reachable. Returns the keyId so the caller can
         *     confirm which key is in use without echoing the secret, the
         *     API surface version, and a server-side timestamp for
         *     clock-skew checks.
         *
         *     Authentication: ANY active API key. Unlike every other v1
         *     operation, this endpoint does NOT require a specific scope
         *     — a brand-new, scopeless key returns 200 here. This makes
         *     it the natural first call when wiring up the SDK.
         *
         *     Versioning: shipped in v1.1.0 (SemVer minor — additive
         *     only). See `docs/api/versioning.md`.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API key introspection
         * @description Returns the current API key's name, granted scopes,
         *     creation/expiration/last-used timestamps, and the current
         *     rate-limit budget snapshot. The canonical "what can my key
         *     actually do?" check.
         *
         *     Authentication: ANY active API key. Like `/health`, no
         *     specific scope is required - a brand-new, scopeless key
         *     returns 200 here. This makes it useful for debugging "why
         *     am I getting 403?" issues without a chicken-and-egg scope
         *     requirement.
         *
         *     Privacy: never returns the bearer key, the key hash, or
         *     any PHI. The `name` field is the human-readable label set
         *     by the admin who created the key (e.g.
         *     "Production prod-east"); it is safe to surface to the end
         *     user as "you are authenticated as X".
         *
         *     Versioning: shipped in v1.4.0 (SemVer minor - additive
         *     only). See `docs/api/versioning.md`.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List providers
         * @description Returns a paginated list of providers. Supports filtering by
         *     `status` and `npi`. PHI is never included.
         */
        get: operations["listProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one provider (full envelope, no PHI) */
        get: operations["getProvider"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{id}/cv.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a provider's CV as PDF
         * @description Streams a fully-formed Curriculum Vitae as `application/pdf`.
         *     Requires the `providers:cv` scope. The CV includes only data
         *     commonly published in CVs (name, NPI, provider type, education,
         *     licensure, board certs, hospital privileges, work history,
         *     CME log) — never SSN, DOB, DEA, or personal addresses.
         */
        get: operations["getProviderCv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sanctions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sanctions checks */
        get: operations["listSanctions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payer enrollments */
        get: operations["listEnrollments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Canonical v1 error envelope. The body of every non-2xx response
         *     from `/api/v1/*` follows this shape. Clients (including the
         *     in-tree TypeScript SDK) parse `error.code` and `error.message`.
         */
        Error: {
            error: {
                /**
                 * @description Stable machine-readable identifier for the failure
                 *     mode. Snake_case. Part of the contract — never renamed
                 *     without bumping `info.version` and following the
                 *     deprecation policy in `docs/api/versioning.md`.
                 * @example not_found
                 */
                code: string;
                /**
                 * @description Human-readable explanation, may change between releases.
                 * @example Provider not found
                 */
                message: string;
                /**
                 * @description Present on `insufficient_scope` errors — names the
                 *     scope the API key would have needed. Optional on
                 *     other errors.
                 */
                required?: string;
            };
        };
        /**
         * @description Body of a `429 Too Many Requests` response. Extends `Error`
         *     with a `retryAfterSeconds` field that mirrors the
         *     `Retry-After` header so SDKs that don't read response headers
         *     can still back off correctly.
         */
        RateLimitProblem: {
            error: {
                /**
                 * @example rate_limited
                 * @constant
                 */
                code: "rate_limited";
                /** @example Rate limit of 120 requests/min exceeded. Retry in 7s. */
                message: string;
                /**
                 * @description Seconds until the next request is allowed. Always
                 *     matches the `Retry-After` header.
                 * @example 7
                 */
                retryAfterSeconds: number;
            };
        };
        Pagination: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
        };
        /**
         * @description Result of `GET /api/v1/health`. Confirms the supplied API key
         *     is active and the environment is reachable. Never includes
         *     PHI or customer-specific business data beyond the keyId
         *     fingerprint.
         */
        Health: {
            /**
             * @description Always `true` on a 200 response. Reserved for forward-compat.
             * @example true
             */
            ok: boolean;
            /**
             * Format: cuid
             * @description Identifier of the active API key (NOT the secret).
             * @example ck0jm0a4e0000abcd1234efgh
             */
            keyId: string;
            /**
             * @description Semver version of the v1 surface (matches `info.version`).
             * @example 1.7.0
             */
            apiVersion: string;
            /**
             * Format: date-time
             * @description Server-side ISO-8601 UTC timestamp for clock-skew checks.
             * @example 2026-04-18T20:45:00.000Z
             */
            time: string;
        };
        /**
         * @description Result of `GET /api/v1/me`. The canonical "what can my API
         *     key actually do?" view. Includes the key's name, granted
         *     scopes, lifecycle timestamps, and the current rate-limit
         *     budget snapshot. Never includes the bearer key, the key
         *     hash, or any PHI. Available since spec v1.4.0.
         */
        Me: {
            /**
             * @description Identifier of the active API key (NOT the secret).
             * @example ck0jm0a4e0000abcd1234efgh
             */
            keyId: string;
            /**
             * @description Human-readable label set by the admin who created the key
             *     (e.g. "Production prod-east"). Safe to surface verbatim
             *     to the end user.
             * @example Production prod-east
             */
            name: string;
            /**
             * @description Granted scopes from the API_SCOPES vocabulary. Order is
             *     stable across calls; an empty array means the key is
             *     authenticated but cannot call any scoped operation.
             * @example [
             *       "providers:read",
             *       "sanctions:read"
             *     ]
             */
            scopes: ("providers:read" | "providers:cv" | "sanctions:read" | "enrollments:read" | "fhir:read")[];
            /**
             * Format: date-time
             * @description ISO-8601 UTC timestamp when the key was issued.
             * @example 2026-01-15T10:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description ISO-8601 UTC expiry timestamp. `null` means the key never
             *     expires (admin-issued, indefinite). The `/me` call still
             *     returns 200 right up to the moment of expiry; the next
             *     scoped call after expiry returns 401 with
             *     `code: "expired_api_key"`.
             * @example 2027-01-15T10:30:00.000Z
             */
            expiresAt: string | null;
            /**
             * Format: date-time
             * @description ISO-8601 UTC timestamp of the most recent successful
             *     authentication. `null` for keys that have never been
             *     used. Updated best-effort on every authenticated request.
             * @example 2026-04-18T22:14:33.123Z
             */
            lastUsedAt: string | null;
            /**
             * @description Snapshot of the current per-key rate-limit budget. The
             *     same numbers are also surfaced on the `X-RateLimit-*`
             *     response headers (see §3.3 of `docs/api/versioning.md`).
             *     `null` only on the (unlikely) older deployments that
             *     haven't yet adopted the rate-limit contract.
             */
            rateLimit: {
                /**
                 * @description Maximum requests allowed in the current fixed window.
                 * @example 120
                 */
                limit: number;
                /**
                 * @description Requests still available in the current window.
                 * @example 117
                 */
                remaining: number;
                /**
                 * @description Unix-seconds (UTC) when the window resets.
                 * @example 1739887200
                 */
                resetUnixSeconds: number;
            } | null;
        };
        /**
         * @description Lifecycle stage of the provider record.
         * @enum {string}
         */
        ProviderStatus: "INVITED" | "APPLICATION_IN_PROGRESS" | "VERIFICATION_IN_PROGRESS" | "COMMITTEE_REVIEW" | "APPROVED" | "DENIED" | "TERMINATED" | "SUSPENDED";
        /** @enum {string} */
        SanctionsResult: "CLEAR" | "MATCH" | "REVIEW_REQUIRED";
        /** @enum {string} */
        EnrollmentStatus: "NOT_STARTED" | "IN_PROGRESS" | "SUBMITTED" | "APPROVED" | "DENIED" | "TERMINATED";
        ProviderType: {
            name?: string;
            abbreviation?: string;
        };
        ProviderSummary: {
            /** Format: cuid */
            id: string;
            legalFirstName: string;
            legalLastName: string;
            npi?: string | null;
            status: components["schemas"]["ProviderStatus"];
            providerType?: components["schemas"]["ProviderType"];
            /** Format: date-time */
            approvedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ProviderDetail: components["schemas"]["ProviderSummary"] & {
            legalMiddleName?: string | null;
            caqhId?: string | null;
            /** Format: date-time */
            updatedAt?: string;
            profile?: {
                specialtyPrimary?: string | null;
                facilityAssignment?: string | null;
                jobTitle?: string | null;
            } | null;
            licenses?: {
                /** Format: cuid */
                id?: string;
                state?: string;
                licenseType?: string;
                status?: string;
                /** Format: date */
                expirationDate?: string | null;
            }[];
            enrollments?: {
                /** Format: cuid */
                id?: string;
                payerName?: string;
                status?: components["schemas"]["EnrollmentStatus"];
                /** Format: date */
                effectiveDate?: string | null;
            }[];
            expirables?: {
                /** Format: cuid */
                id?: string;
                expirableType?: string;
                status?: string;
                /** Format: date */
                expirationDate?: string | null;
            }[];
        };
        ProvidersPage: {
            data: components["schemas"]["ProviderSummary"][];
            pagination: components["schemas"]["Pagination"];
        };
        SanctionsCheck: {
            /** Format: cuid */
            id: string;
            /** @example OIG_LEIE */
            source: string;
            result: components["schemas"]["SanctionsResult"];
            /** Format: date-time */
            runDate: string;
            triggeredBy?: string | null;
            provider?: {
                /** Format: cuid */
                id?: string;
                legalFirstName?: string;
                legalLastName?: string;
                npi?: string | null;
            };
        };
        SanctionsPage: {
            data: components["schemas"]["SanctionsCheck"][];
            pagination: components["schemas"]["Pagination"];
        };
        Enrollment: {
            /** Format: cuid */
            id: string;
            payerName: string;
            enrollmentType?: string | null;
            status: components["schemas"]["EnrollmentStatus"];
            /** Format: date */
            effectiveDate?: string | null;
            /** Format: date-time */
            submittedAt?: string | null;
            provider?: {
                /** Format: cuid */
                id?: string;
                legalFirstName?: string;
                legalLastName?: string;
                npi?: string | null;
            };
        };
        EnrollmentsPage: {
            data: components["schemas"]["Enrollment"][];
            pagination: components["schemas"]["Pagination"];
        };
    };
    responses: {
        /** @description Missing or invalid API key. */
        Unauthorized: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                Deprecation: components["headers"]["Deprecation"];
                Sunset: components["headers"]["Sunset"];
                Link: components["headers"]["Link"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description API key valid but lacks the required scope. */
        Forbidden: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                Deprecation: components["headers"]["Deprecation"];
                Sunset: components["headers"]["Sunset"];
                Link: components["headers"]["Link"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                Deprecation: components["headers"]["Deprecation"];
                Sunset: components["headers"]["Sunset"];
                Link: components["headers"]["Link"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Conditional GET cache hit (since v1.6.0). The caller sent
         *     `If-None-Match` with an ETag that matches the current
         *     representation. The response body is empty (zero bytes per
         *     RFC 9110 §15.4.5); the `ETag`, `X-Request-Id`, and
         *     rate-limit headers are still present, and (since v1.7.0)
         *     any `Deprecation` / `Sunset` / `Link` advisory headers
         *     applicable to the operation also fire on the 304 — a
         *     client polling on `If-None-Match` must still find out
         *     about deprecation.
         */
        NotModified: {
            headers: {
                ETag: components["headers"]["ETag"];
                "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                "X-Request-Id": components["headers"]["RequestId"];
                Deprecation: components["headers"]["Deprecation"];
                Sunset: components["headers"]["Sunset"];
                Link: components["headers"]["Link"];
                [name: string]: unknown;
            };
            content?: never;
        };
        /**
         * @description Too many requests for this key. The body is a
         *     `RateLimitProblem`. The `Retry-After` header (seconds) tells
         *     you when the next request is allowed; the standard
         *     `X-RateLimit-*` headers (also present on every successful
         *     response since v1.2.0) describe your budget.
         */
        RateLimited: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                "X-Request-Id": components["headers"]["RequestId"];
                Deprecation: components["headers"]["Deprecation"];
                Sunset: components["headers"]["Sunset"];
                Link: components["headers"]["Link"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RateLimitProblem"];
            };
        };
    };
    parameters: {
        /**
         * @description Optional caller-supplied correlation id. If supplied and it
         *     matches `^[A-Za-z0-9_\-]{8,128}$` the server honours it and
         *     echoes it back on the response. Otherwise the server
         *     generates one. Pair this with your client-side log lines for
         *     end-to-end tracing. Available since v1.3.0.
         */
        RequestIdHeader: string;
        /**
         * @description Conditional GET — supply the `ETag` value the server returned
         *     on a previous response and, if nothing has changed, the
         *     server replies `304 Not Modified` with an empty body. Either
         *     the literal `*` (wildcard, always matches a current
         *     representation) or one or more quoted ETag tokens
         *     (`W/"<hex>"` or `"<hex>"`), comma-separated. Weak
         *     comparison per RFC 9110 §13.1.2 — a strong-form token
         *     (`"abc"`) matches the corresponding weak-form ETag
         *     (`W/"abc"`). Available since v1.6.0.
         * @example W/"deadbeefcafebabe1234567890abcdef12345678"
         */
        IfNoneMatchHeader: string;
        /** @description 1-based page index. Default 1. */
        Page: number;
        /** @description Items per page (max 100). Default 25. */
        Limit: number;
    };
    requestBodies: never;
    headers: {
        /**
         * @description Correlation id for this request/response pair. If the inbound
         *     request supplied a valid `X-Request-Id` we honour it;
         *     otherwise we generate one server-side as `req_<hex>`.
         *     Present on every response (2xx and non-2xx). Format:
         *     `^[A-Za-z0-9_\-]{8,128}$`. Pass it to support to look up the
         *     full audit + log trail in O(1). Available since v1.3.0.
         */
        RequestId: string;
        /**
         * @description Maximum requests allowed in the current fixed window for the
         *     authenticated API key. Stable across the window. Present on
         *     every successful 2xx response and on the 429 rejection.
         */
        RateLimitLimit: number;
        /**
         * @description Requests still available in the current window (>= 0).
         *     Decrements on every accepted request. On a 429 this is `0`.
         */
        RateLimitRemaining: number;
        /**
         * @description Unix-seconds (UTC) timestamp when the current window resets
         *     and `X-RateLimit-Remaining` returns to `X-RateLimit-Limit`.
         */
        RateLimitReset: number;
        /**
         * @description Seconds the client should wait before retrying. Always >= 1.
         *     Present only on `429` responses.
         */
        RetryAfter: number;
        /**
         * @description RFC 8288 web links, comma-separated. Carries up to three
         *     independent classes of entries; **only the entries that
         *     apply to a given response are emitted**. Use the SDK's
         *     `parseLinkHeader(headers.get("Link"))` helper to turn it
         *     into a `{ rel: url }` map.
         *
         *       1. **Pagination** (since v1.5.0). Present on every
         *          paginated list response when the result set has at
         *          least one page. Always emits `first` and `last`;
         *          emits `prev` when `page > 1` and `next` when
         *          `page < totalPages`.
         *       2. **Deprecation pointers** (since v1.7.0). When the
         *          current operation is on a deprecation path, emits
         *          `rel="deprecation"` and `rel="sunset"` entries
         *          pointing at the upgrade guide, plus an optional
         *          `rel="successor-version"` entry pointing at the
         *          replacement endpoint when one exists.
         *
         *     The pagination + deprecation entries are independent: a
         *     deprecated paginated endpoint emits BOTH classes of links
         *     in the same `Link` header.
         */
        Link: string;
        /**
         * @description Weak entity-tag for the response body, derived from a stable
         *     SHA-1 hash of the canonicalized cacheable subset of the
         *     payload. Always in `W/"<40-hex>"` form. Echo this back as
         *     `If-None-Match: "<etag>"` on the next poll to receive a
         *     `304 Not Modified` when nothing has changed. The hash is
         *     computed AFTER excluding per-request fields (timestamps,
         *     rate-limit snapshots, last-used markers) so the validator
         *     is stable across cosmetic refreshes. Available since v1.6.0.
         */
        ETag: string;
        /**
         * @description RFC 9745 advisory header. **Present only when this operation
         *     has entered its deprecation window** — its absence means the
         *     operation is on the supported path. Value is the
         *     structured-fields integer form: an `@`-prefixed Unix-seconds
         *     timestamp recording when deprecation took effect (e.g.
         *     `@1796083200` is `2026-12-01T00:00:00Z`).
         *
         *     When `Deprecation` is present, `Sunset` is also present, and
         *     the `Link` header carries `rel="deprecation"` (and where
         *     applicable `rel="sunset"`, `rel="successor-version"`)
         *     entries pointing at the upgrade guide and replacement
         *     endpoint. Available since v1.7.0.
         */
        Deprecation: string;
        /**
         * @description RFC 8594 advisory header. **Present only when this operation
         *     has entered its deprecation window** — pairs with the
         *     `Deprecation` header. Value is an HTTP-date (IMF-fixdate per
         *     RFC 9110 §5.6.7) marking the wall-clock at which the
         *     operation will start returning `410 Gone`. Always at least
         *     180 days in the future at first publication; the policy
         *     lives in `docs/api/versioning.md` §4. Available since
         *     v1.7.0.
         */
        Sunset: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Optional caller-supplied correlation id. If supplied and it
                 *     matches `^[A-Za-z0-9_\-]{8,128}$` the server honours it and
                 *     echoes it back on the response. Otherwise the server
                 *     generates one. Pair this with your client-side log lines for
                 *     end-to-end tracing. Available since v1.3.0.
                 */
                "X-Request-Id"?: components["parameters"]["RequestIdHeader"];
                /**
                 * @description Conditional GET — supply the `ETag` value the server returned
                 *     on a previous response and, if nothing has changed, the
                 *     server replies `304 Not Modified` with an empty body. Either
                 *     the literal `*` (wildcard, always matches a current
                 *     representation) or one or more quoted ETag tokens
                 *     (`W/"<hex>"` or `"<hex>"`), comma-separated. Weak
                 *     comparison per RFC 9110 §13.1.2 — a strong-form token
                 *     (`"abc"`) matches the corresponding weak-form ETag
                 *     (`W/"abc"`). Available since v1.6.0.
                 * @example W/"deadbeefcafebabe1234567890abcdef12345678"
                 */
                "If-None-Match"?: components["parameters"]["IfNoneMatchHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                    "X-Request-Id": components["headers"]["RequestId"];
                    Deprecation: components["headers"]["Deprecation"];
                    Sunset: components["headers"]["Sunset"];
                    Link: components["headers"]["Link"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            304: components["responses"]["NotModified"];
            /** @description Missing, invalid, expired, or revoked API key. */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    Deprecation: components["headers"]["Deprecation"];
                    Sunset: components["headers"]["Sunset"];
                    Link: components["headers"]["Link"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Optional caller-supplied correlation id. If supplied and it
                 *     matches `^[A-Za-z0-9_\-]{8,128}$` the server honours it and
                 *     echoes it back on the response. Otherwise the server
                 *     generates one. Pair this with your client-side log lines for
                 *     end-to-end tracing. Available since v1.3.0.
                 */
                "X-Request-Id"?: components["parameters"]["RequestIdHeader"];
                /**
                 * @description Conditional GET — supply the `ETag` value the server returned
                 *     on a previous response and, if nothing has changed, the
                 *     server replies `304 Not Modified` with an empty body. Either
                 *     the literal `*` (wildcard, always matches a current
                 *     representation) or one or more quoted ETag tokens
                 *     (`W/"<hex>"` or `"<hex>"`), comma-separated. Weak
                 *     comparison per RFC 9110 §13.1.2 — a strong-form token
                 *     (`"abc"`) matches the corresponding weak-form ETag
                 *     (`W/"abc"`). Available since v1.6.0.
                 * @example W/"deadbeefcafebabe1234567890abcdef12345678"
                 */
                "If-None-Match"?: components["parameters"]["IfNoneMatchHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API key introspection result. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                    "X-Request-Id": components["headers"]["RequestId"];
                    Deprecation: components["headers"]["Deprecation"];
                    Sunset: components["headers"]["Sunset"];
                    Link: components["headers"]["Link"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            304: components["responses"]["NotModified"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    listProviders: {
        parameters: {
            query?: {
                /** @description 1-based page index. Default 1. */
                page?: components["parameters"]["Page"];
                /** @description Items per page (max 100). Default 25. */
                limit?: components["parameters"]["Limit"];
                status?: components["schemas"]["ProviderStatus"];
                /** @description Exact-match NPI filter. */
                npi?: string;
            };
            header?: {
                /**
                 * @description Optional caller-supplied correlation id. If supplied and it
                 *     matches `^[A-Za-z0-9_\-]{8,128}$` the server honours it and
                 *     echoes it back on the response. Otherwise the server
                 *     generates one. Pair this with your client-side log lines for
                 *     end-to-end tracing. Available since v1.3.0.
                 */
                "X-Request-Id"?: components["parameters"]["RequestIdHeader"];
                /**
                 * @description Conditional GET — supply the `ETag` value the server returned
                 *     on a previous response and, if nothing has changed, the
                 *     server replies `304 Not Modified` with an empty body. Either
                 *     the literal `*` (wildcard, always matches a current
                 *     representation) or one or more quoted ETag tokens
                 *     (`W/"<hex>"` or `"<hex>"`), comma-separated. Weak
                 *     comparison per RFC 9110 §13.1.2 — a strong-form token
                 *     (`"abc"`) matches the corresponding weak-form ETag
                 *     (`W/"abc"`). Available since v1.6.0.
                 * @example W/"deadbeefcafebabe1234567890abcdef12345678"
                 */
                "If-None-Match"?: components["parameters"]["IfNoneMatchHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of providers. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                    Link: components["headers"]["Link"];
                    "X-Request-Id": components["headers"]["RequestId"];
                    Deprecation: components["headers"]["Deprecation"];
                    Sunset: components["headers"]["Sunset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersPage"];
                };
            };
            304: components["responses"]["NotModified"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    getProvider: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Optional caller-supplied correlation id. If supplied and it
                 *     matches `^[A-Za-z0-9_\-]{8,128}$` the server honours it and
                 *     echoes it back on the response. Otherwise the server
                 *     generates one. Pair this with your client-side log lines for
                 *     end-to-end tracing. Available since v1.3.0.
                 */
                "X-Request-Id"?: components["parameters"]["RequestIdHeader"];
                /**
                 * @description Conditional GET — supply the `ETag` value the server returned
                 *     on a previous response and, if nothing has changed, the
                 *     server replies `304 Not Modified` with an empty body. Either
                 *     the literal `*` (wildcard, always matches a current
                 *     representation) or one or more quoted ETag tokens
                 *     (`W/"<hex>"` or `"<hex>"`), comma-separated. Weak
                 *     comparison per RFC 9110 §13.1.2 — a strong-form token
                 *     (`"abc"`) matches the corresponding weak-form ETag
                 *     (`W/"abc"`). Available since v1.6.0.
                 * @example W/"deadbeefcafebabe1234567890abcdef12345678"
                 */
                "If-None-Match"?: components["parameters"]["IfNoneMatchHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider envelope. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                    "X-Request-Id": components["headers"]["RequestId"];
                    Deprecation: components["headers"]["Deprecation"];
                    Sunset: components["headers"]["Sunset"];
                    Link: components["headers"]["Link"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProviderDetail"];
                    };
                };
            };
            304: components["responses"]["NotModified"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    getProviderCv: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Optional caller-supplied correlation id. If supplied and it
                 *     matches `^[A-Za-z0-9_\-]{8,128}$` the server honours it and
                 *     echoes it back on the response. Otherwise the server
                 *     generates one. Pair this with your client-side log lines for
                 *     end-to-end tracing. Available since v1.3.0.
                 */
                "X-Request-Id"?: components["parameters"]["RequestIdHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF CV stream. */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    "Content-Length"?: number;
                    "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                    "X-Request-Id": components["headers"]["RequestId"];
                    Deprecation: components["headers"]["Deprecation"];
                    Sunset: components["headers"]["Sunset"];
                    Link: components["headers"]["Link"];
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    listSanctions: {
        parameters: {
            query?: {
                /** @description 1-based page index. Default 1. */
                page?: components["parameters"]["Page"];
                /** @description Items per page (max 100). Default 25. */
                limit?: components["parameters"]["Limit"];
                providerId?: string;
                result?: components["schemas"]["SanctionsResult"];
            };
            header?: {
                /**
                 * @description Optional caller-supplied correlation id. If supplied and it
                 *     matches `^[A-Za-z0-9_\-]{8,128}$` the server honours it and
                 *     echoes it back on the response. Otherwise the server
                 *     generates one. Pair this with your client-side log lines for
                 *     end-to-end tracing. Available since v1.3.0.
                 */
                "X-Request-Id"?: components["parameters"]["RequestIdHeader"];
                /**
                 * @description Conditional GET — supply the `ETag` value the server returned
                 *     on a previous response and, if nothing has changed, the
                 *     server replies `304 Not Modified` with an empty body. Either
                 *     the literal `*` (wildcard, always matches a current
                 *     representation) or one or more quoted ETag tokens
                 *     (`W/"<hex>"` or `"<hex>"`), comma-separated. Weak
                 *     comparison per RFC 9110 §13.1.2 — a strong-form token
                 *     (`"abc"`) matches the corresponding weak-form ETag
                 *     (`W/"abc"`). Available since v1.6.0.
                 * @example W/"deadbeefcafebabe1234567890abcdef12345678"
                 */
                "If-None-Match"?: components["parameters"]["IfNoneMatchHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of sanctions checks. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                    "X-Request-Id": components["headers"]["RequestId"];
                    Link: components["headers"]["Link"];
                    Deprecation: components["headers"]["Deprecation"];
                    Sunset: components["headers"]["Sunset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SanctionsPage"];
                };
            };
            304: components["responses"]["NotModified"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    listEnrollments: {
        parameters: {
            query?: {
                /** @description 1-based page index. Default 1. */
                page?: components["parameters"]["Page"];
                /** @description Items per page (max 100). Default 25. */
                limit?: components["parameters"]["Limit"];
                status?: components["schemas"]["EnrollmentStatus"];
                /** @description Case-insensitive substring filter on payer name. */
                payer?: string;
            };
            header?: {
                /**
                 * @description Optional caller-supplied correlation id. If supplied and it
                 *     matches `^[A-Za-z0-9_\-]{8,128}$` the server honours it and
                 *     echoes it back on the response. Otherwise the server
                 *     generates one. Pair this with your client-side log lines for
                 *     end-to-end tracing. Available since v1.3.0.
                 */
                "X-Request-Id"?: components["parameters"]["RequestIdHeader"];
                /**
                 * @description Conditional GET — supply the `ETag` value the server returned
                 *     on a previous response and, if nothing has changed, the
                 *     server replies `304 Not Modified` with an empty body. Either
                 *     the literal `*` (wildcard, always matches a current
                 *     representation) or one or more quoted ETag tokens
                 *     (`W/"<hex>"` or `"<hex>"`), comma-separated. Weak
                 *     comparison per RFC 9110 §13.1.2 — a strong-form token
                 *     (`"abc"`) matches the corresponding weak-form ETag
                 *     (`W/"abc"`). Available since v1.6.0.
                 * @example W/"deadbeefcafebabe1234567890abcdef12345678"
                 */
                "If-None-Match"?: components["parameters"]["IfNoneMatchHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of enrollments. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                    "X-Request-Id": components["headers"]["RequestId"];
                    Link: components["headers"]["Link"];
                    Deprecation: components["headers"]["Deprecation"];
                    Sunset: components["headers"]["Sunset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentsPage"];
                };
            };
            304: components["responses"]["NotModified"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
}
