/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API key + environment health probe
         * @description Verifies that the supplied API key is active and that the
         *     environment is reachable. Returns the keyId so the caller can
         *     confirm which key is in use without echoing the secret, the
         *     API surface version, and a server-side timestamp for
         *     clock-skew checks.
         *
         *     Authentication: ANY active API key. Unlike every other v1
         *     operation, this endpoint does NOT require a specific scope
         *     — a brand-new, scopeless key returns 200 here. This makes
         *     it the natural first call when wiring up the SDK.
         *
         *     Versioning: shipped in v1.1.0 (SemVer minor — additive
         *     only). See `docs/api/versioning.md`.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List providers
         * @description Returns a paginated list of providers. Supports filtering by
         *     `status` and `npi`. PHI is never included.
         */
        get: operations["listProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one provider (full envelope, no PHI) */
        get: operations["getProvider"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{id}/cv.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a provider's CV as PDF
         * @description Streams a fully-formed Curriculum Vitae as `application/pdf`.
         *     Requires the `providers:cv` scope. The CV includes only data
         *     commonly published in CVs (name, NPI, provider type, education,
         *     licensure, board certs, hospital privileges, work history,
         *     CME log) — never SSN, DOB, DEA, or personal addresses.
         */
        get: operations["getProviderCv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sanctions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sanctions checks */
        get: operations["listSanctions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payer enrollments */
        get: operations["listEnrollments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @example PROVIDER_NOT_FOUND */
                code: string;
                /** @example Provider not found */
                message: string;
            };
        };
        Pagination: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
        };
        /**
         * @description Result of `GET /api/v1/health`. Confirms the supplied API key
         *     is active and the environment is reachable. Never includes
         *     PHI or customer-specific business data beyond the keyId
         *     fingerprint.
         */
        Health: {
            /**
             * @description Always `true` on a 200 response. Reserved for forward-compat.
             * @example true
             */
            ok: boolean;
            /**
             * Format: cuid
             * @description Identifier of the active API key (NOT the secret).
             * @example ck0jm0a4e0000abcd1234efgh
             */
            keyId: string;
            /**
             * @description Semver version of the v1 surface (matches `info.version`).
             * @example 1.1.0
             */
            apiVersion: string;
            /**
             * Format: date-time
             * @description Server-side ISO-8601 UTC timestamp for clock-skew checks.
             * @example 2026-04-18T20:45:00.000Z
             */
            time: string;
        };
        /**
         * @description Lifecycle stage of the provider record.
         * @enum {string}
         */
        ProviderStatus: "INVITED" | "APPLICATION_IN_PROGRESS" | "VERIFICATION_IN_PROGRESS" | "COMMITTEE_REVIEW" | "APPROVED" | "DENIED" | "TERMINATED" | "SUSPENDED";
        /** @enum {string} */
        SanctionsResult: "CLEAR" | "MATCH" | "REVIEW_REQUIRED";
        /** @enum {string} */
        EnrollmentStatus: "NOT_STARTED" | "IN_PROGRESS" | "SUBMITTED" | "APPROVED" | "DENIED" | "TERMINATED";
        ProviderType: {
            name?: string;
            abbreviation?: string;
        };
        ProviderSummary: {
            /** Format: cuid */
            id: string;
            legalFirstName: string;
            legalLastName: string;
            npi?: string | null;
            status: components["schemas"]["ProviderStatus"];
            providerType?: components["schemas"]["ProviderType"];
            /** Format: date-time */
            approvedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ProviderDetail: components["schemas"]["ProviderSummary"] & {
            legalMiddleName?: string | null;
            caqhId?: string | null;
            /** Format: date-time */
            updatedAt?: string;
            profile?: {
                specialtyPrimary?: string | null;
                facilityAssignment?: string | null;
                jobTitle?: string | null;
            } | null;
            licenses?: {
                /** Format: cuid */
                id?: string;
                state?: string;
                licenseType?: string;
                status?: string;
                /** Format: date */
                expirationDate?: string | null;
            }[];
            enrollments?: {
                /** Format: cuid */
                id?: string;
                payerName?: string;
                status?: components["schemas"]["EnrollmentStatus"];
                /** Format: date */
                effectiveDate?: string | null;
            }[];
            expirables?: {
                /** Format: cuid */
                id?: string;
                expirableType?: string;
                status?: string;
                /** Format: date */
                expirationDate?: string | null;
            }[];
        };
        ProvidersPage: {
            data: components["schemas"]["ProviderSummary"][];
            pagination: components["schemas"]["Pagination"];
        };
        SanctionsCheck: {
            /** Format: cuid */
            id: string;
            /** @example OIG_LEIE */
            source: string;
            result: components["schemas"]["SanctionsResult"];
            /** Format: date-time */
            runDate: string;
            triggeredBy?: string | null;
            provider?: {
                /** Format: cuid */
                id?: string;
                legalFirstName?: string;
                legalLastName?: string;
                npi?: string | null;
            };
        };
        SanctionsPage: {
            data: components["schemas"]["SanctionsCheck"][];
            pagination: components["schemas"]["Pagination"];
        };
        Enrollment: {
            /** Format: cuid */
            id: string;
            payerName: string;
            enrollmentType?: string | null;
            status: components["schemas"]["EnrollmentStatus"];
            /** Format: date */
            effectiveDate?: string | null;
            /** Format: date-time */
            submittedAt?: string | null;
            provider?: {
                /** Format: cuid */
                id?: string;
                legalFirstName?: string;
                legalLastName?: string;
                npi?: string | null;
            };
        };
        EnrollmentsPage: {
            data: components["schemas"]["Enrollment"][];
            pagination: components["schemas"]["Pagination"];
        };
    };
    responses: {
        /** @description Missing or invalid API key. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description API key valid but lacks the required scope. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests for this key — see `Retry-After` header. */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description 1-based page index. Default 1. */
        Page: number;
        /** @description Items per page (max 100). Default 25. */
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Missing, invalid, expired, or revoked API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    listProviders: {
        parameters: {
            query?: {
                /** @description 1-based page index. Default 1. */
                page?: components["parameters"]["Page"];
                /** @description Items per page (max 100). Default 25. */
                limit?: components["parameters"]["Limit"];
                status?: components["schemas"]["ProviderStatus"];
                /** @description Exact-match NPI filter. */
                npi?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of providers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    getProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider envelope. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProviderDetail"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    getProviderCv: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF CV stream. */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    "Content-Length"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listSanctions: {
        parameters: {
            query?: {
                /** @description 1-based page index. Default 1. */
                page?: components["parameters"]["Page"];
                /** @description Items per page (max 100). Default 25. */
                limit?: components["parameters"]["Limit"];
                providerId?: string;
                result?: components["schemas"]["SanctionsResult"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of sanctions checks. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SanctionsPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    listEnrollments: {
        parameters: {
            query?: {
                /** @description 1-based page index. Default 1. */
                page?: components["parameters"]["Page"];
                /** @description Items per page (max 100). Default 25. */
                limit?: components["parameters"]["Limit"];
                status?: components["schemas"]["EnrollmentStatus"];
                /** @description Case-insensitive substring filter on payer name. */
                payer?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of enrollments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentsPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
}
