/**
 * Wave 5.2 — public sandbox API: provider list.
 *
 * Returns deterministic synthetic provider data so an evaluator can
 * wire a POC without onboarding. NEVER touches the database; the
 * payload is generated by `synthProviders()` from a deterministic seed.
 *
 * Anti-weakening (STANDARD.md §4.2):
 *   - DO NOT extend this endpoint to read live data without an ADR.
 *   - DO NOT lift the cache headers — sandbox results are immutable.
 */
import { NextResponse } from "next/server";
import { synthProviders } from "@/lib/sandbox/synth";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET(request: Request) {
  const url = new URL(request.url);
  const page = Math.max(1, Number(url.searchParams.get("page") ?? 1));
  const pageSize = 25;

  const all = synthProviders();
  const start = (page - 1) * pageSize;
  const data = all.slice(start, start + pageSize).map((p) => ({
    id: p.id,
    name: p.name,
    npi: p.npi,
    primaryState: p.primaryState,
    status: p.status,
  }));

  return NextResponse.json(
    { data, page, pageSize, total: all.length },
    {
      headers: {
        "Cache-Control": "public, max-age=60, s-maxage=300",
        "X-Sandbox": "ecred-v1",
      },
    },
  );
}

export const POST = methodNotAllowed;
export const PUT = methodNotAllowed;
export const PATCH = methodNotAllowed;
export const DELETE = methodNotAllowed;

function methodNotAllowed() {
  return NextResponse.json(
    { error: "method_not_allowed", message: "The sandbox is read-only." },
    { status: 405, headers: { Allow: "GET" } },
  );
}
