/**
 * GET /api/v1/postman.json
 *
 * Wave 11 (2026-04-18). Serves the auto-generated Postman v2.1.0
 * collection covering every documented operation in
 * `docs/api/openapi-v1.yaml`. Customers download this once and
 * import into Postman / Insomnia / Bruno.
 *
 * Source: `public/api/v1/postman.json`, regenerated by
 * `npm run postman:gen`. The generator (and the contract test
 * `tests/contract/pillar-j-postman.spec.ts`) ensure the collection
 * is in lockstep with the OpenAPI spec — adding a new endpoint to
 * the spec without regenerating the collection MUST fail CI.
 *
 * Anti-weakening: this route MUST NOT modify the JSON. The
 * collection is a build artifact; the route is a delivery channel.
 */

import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { NextResponse } from "next/server";

export const runtime = "nodejs";

let cachedCollection: string | null = null;

async function loadCollection(): Promise<string> {
  if (cachedCollection) return cachedCollection;
  const path = join(process.cwd(), "public", "api", "v1", "postman.json");
  cachedCollection = await readFile(path, "utf-8");
  return cachedCollection;
}

export async function GET(): Promise<NextResponse> {
  const json = await loadCollection();
  return new NextResponse(json, {
    status: 200,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      "Content-Disposition":
        'attachment; filename="ecredentialing-v1.postman_collection.json"',
      "Cache-Control": "public, max-age=300, s-maxage=3600",
      "X-Content-Type-Options": "nosniff",
    },
  });
}
