/**
 * Pillar J -- API contract (per `docs/qa/STANDARD.md` §1.J).
 *
 * Two snapshot gates:
 *
 *   1. tRPC procedure surface matches docs/qa/inventories/trpc-inventory.json.
 *      Adding or removing a procedure without updating the inventory is a
 *      contract drift -- §4 hard-fail #8.
 *   2. /api/* surface matches docs/qa/inventories/api-inventory.json,
 *      same gate.
 *
 * The inventories are regenerated by `npm run qa:inventories`. If a PR
 * adds a procedure without re-running the script, this spec fails.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

interface TrpcEntry { router: string; procedure: string; kind: string; file: string; }
interface ApiEntry { route: string; methods: string[]; file: string; dynamic: boolean; }

const ROOT = join(process.cwd());
const TRPC = JSON.parse(readFileSync(join(ROOT, "docs/qa/inventories/trpc-inventory.json"), "utf8")) as TrpcEntry[];
const API = JSON.parse(readFileSync(join(ROOT, "docs/qa/inventories/api-inventory.json"), "utf8")) as ApiEntry[];

describe("pillar-J: contract surface", () => {
  it("tRPC inventory has at least 50 procedures (sanity floor)", () => {
    expect(TRPC.length, "tRPC procedure count dropped -- regenerate inventory").toBeGreaterThanOrEqual(50);
  });

  it("API inventory exposes /api/health, /api/ready, /api/metrics", () => {
    const routes = new Set(API.map((a) => a.route));
    for (const required of ["/api/health", "/api/ready", "/api/metrics"]) {
      expect(routes.has(required), `missing required route ${required}`).toBe(true);
    }
  });

  it("API inventory exposes the FHIR endpoints we ship", () => {
    const routes = new Set(API.map((a) => a.route));
    for (const required of [
      "/api/fhir/metadata",
      "/api/fhir/Practitioner",
      "/api/fhir/Practitioner/[id]",
      "/api/fhir/PractitionerRole",
      "/api/fhir/Organization",
      "/api/fhir/Location",
      "/api/fhir/Endpoint",
    ]) {
      expect(routes.has(required), `FHIR endpoint missing from API inventory: ${required}`).toBe(true);
    }
  });

  it("every tRPC entry references a real source file", () => {
    for (const e of TRPC) {
      expect(e.file, `tRPC entry missing file: ${e.router}.${e.procedure}`).toMatch(/\.ts$/);
    }
  });
});
