#!/usr/bin/env python3
"""
scripts/standards/build-prompt-workbook.py

Generates `docs/standards/PROMPTS.xlsx`, a formatted workbook of the
HDPulseAI Standards prompt library so the developer can browse,
filter, and copy-paste prompts without scrolling a long markdown file.

Sheets:

  1. "Read me"
        How to use the workbook, what APPLY vs VERIFY means, how
        placeholders work, how to keep the workbook in sync with the
        canonical PROMPTS.md.

  2. "Sections"
        The 10 categories. Explains what each section is for,
        when to use prompts from it, and how many prompts it contains.

  3. "All prompts"
        Flat table of every prompt (27 rows). Columns:
          Section | ID | Type | Title | Pillar(s) | When to use
            | Desired outcome | Prompt body
        Frozen header, autofilter on every column, color-coded Type,
        wrapped prompt body, sized for at-a-glance scanning.

  4. "Workflows"
        Recommended prompt sequences for common scenarios
        (new feature, bug-fix, deploy, onboarding-a-repo, etc.).
        Helps the developer know "which prompts in which order".

The workbook is regenerated by re-running this script. The prompt
data lives below as PROMPTS = [...]; edit there and re-run when
PROMPTS.md changes. The script is the single source of truth for
the workbook's content; PROMPTS.md is the single source of truth
for the prompt bodies the agent reads. They are kept in sync by
hand (small edit surface).

Anti-weakening (STANDARD.md §4.2):
  - This script is informational; it never modifies a spec, does
    not lower a coverage threshold, does not skip a test.
  - Editing the workbook does not change the standard. The standard
    lives in docs/qa/STANDARD.md and the global Cursor rule.

Usage:
  python scripts/standards/build-prompt-workbook.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

try:
    from openpyxl import Workbook
    from openpyxl.styles import (
        Alignment,
        Border,
        Font,
        PatternFill,
        Side,
    )
    from openpyxl.utils import get_column_letter
    from openpyxl.worksheet.table import Table, TableStyleInfo
except ImportError as e:
    print(
        "FATAL: openpyxl not installed. Run: python -m pip install openpyxl",
        file=sys.stderr,
    )
    raise

REPO_ROOT = Path(__file__).resolve().parents[2]
OUT_PATH = REPO_ROOT / "docs" / "standards" / "PROMPTS.xlsx"

# ---------------------------------------------------------------------------
# DATA
# ---------------------------------------------------------------------------

SECTIONS = [
    (
        "0",
        "Universal one-liners",
        "Two prompts that wrap any task you don't have a more "
        "specific prompt for. They force the standard's deliverables "
        "(headline reporting block, anti-weakening attestation, "
        "Done. line) regardless of the underlying work.",
        "Default starting point. Pick one of these if no other "
        "section fits.",
        2,
    ),
    (
        "1",
        "Testing (Pillars A–S)",
        "Adds or updates test coverage across the 19 testing pillars: "
        "A functional smoke, B RBAC, E accessibility (axe-core), J "
        "API contract (OpenAPI / RFC 9457), S live-stack reality "
        "(Pillar S surfaces 1–7).",
        "New feature, new route, new role, new API endpoint, missing "
        "coverage flagged by qa:check-coverage.",
        6,
    ),
    (
        "2",
        "Documentation (Pillar Q)",
        "Keeps required documents current with code; opens ADRs for "
        "architectural decisions; audits doc drift read-only.",
        "After any change that ships; after any architectural "
        "decision; before a release.",
        3,
    ),
    (
        "3",
        "UI/UX (Pillars E + F + G)",
        "Accessibility (WCAG 2.1 AA via axe-core), visual regression "
        "(Playwright snapshots in three browsers, three viewports), "
        "responsive layout (mobile 375 / tablet 768 / desktop 1440).",
        "New screen, redesign, accessibility audit, mobile / tablet "
        "bug, design system update.",
        3,
    ),
    (
        "4",
        "Live-stack & dev-loop (Pillar S)",
        "Pillar S surfaces 1–7: bring-up health, schema/migration "
        "parity, sign-in matrix, authenticated session probe, public "
        "surface invariants, named-volume staleness, dev-loop "
        "performance baseline (Turbopack + dynamic-route warmer + "
        "2000 ms re-fetch budget).",
        "Stack bring-up, slow compile (DEF-0014), pre-deploy gate, "
        "post-deploy smoke.",
        3,
    ),
    (
        "5",
        "Security & compliance (Pillars I, P)",
        "DAST / security scans (Pillar I); HIPAA / NCQA / "
        "CMS-0057-F / Joint-Commission compliance tagging (Pillar P).",
        "Security review, compliance attestation, finding triage, "
        "audit prep.",
        2,
    ),
    (
        "6",
        "Defect handling",
        "Opens and closes DEF-#### cards under docs/qa/defects/ per "
        "STANDARD.md §4.1 (Fix-Until-Green) and §4.2 (anti-weakening "
        "attestation).",
        "When something breaks (open card); when a fix is ready to "
        "land (close card).",
        2,
    ),
    (
        "7",
        "Deploy",
        "Push, commit, deploy via .claude/deploy.py, post-deploy "
        "/api/health verification.",
        "Shipping to production; confirming production health after "
        "a deploy.",
        2,
    ),
    (
        "8",
        "Cross-tool, cross-repo",
        "Bootstrapping a new repo, re-bootstrapping every HDPulseAI "
        "repo on this machine, auditing standards propagation.",
        "Onboarding a new repo, after a STANDARD.md version bump, "
        "verifying machine setup.",
        3,
    ),
    (
        "9",
        "Kitchen-sink",
        "One all-in-one 'do the work the right way and prove it' "
        "prompt that walks the full standard cycle: read → plan → "
        "code → test → doc → ship → report.",
        "Long-running, walk-away tasks where you want a single "
        "instruction that covers everything.",
        1,
    ),
]

# Each prompt is a tuple:
#   (section_id, prompt_id, type, title, pillars, when_to_use,
#    desired_outcome, body)
PROMPTS = [
    (
        "0",
        "0.1",
        "APPLY",
        "Default work request",
        "All (A–S)",
        "Anything where no more specific prompt fits.",
        "The change itself + spec + per-screen and per-flow card "
        "updates + the headline reporting block + anti-weakening "
        "attestation + a Done. line if and only if qa:gate is green.",
        (
            "Apply the HDPulseAI QA Standard (see docs/qa/STANDARD.md "
            "in this repo, else ~/.cursor/rules/qa-standard-global.mdc) "
            "to the following task: <your task here>.\n"
            "\n"
            "Required deliverables before you stop:\n"
            "1. The change itself, satisfying every relevant pillar "
            "from A–S.\n"
            "2. A spec under the relevant tests/e2e/<pillar>/ folder, "
            "plus per-screen and per-flow card updates.\n"
            "3. The headline reporting block at the end of your "
            "response (Routes covered:, Roles exercised:, Live stack:, "
            "migrations:, sign-in matrix:, dev-perf:, "
            "Pass/Fail/NotRun, Pillars touched:, Hard-fails cleared:).\n"
            "4. Anti-weakening attestation per STANDARD.md §4.2.\n"
            "5. A Done. line at the very end if (and only if) "
            "npm run qa:gate (or the framework equivalent) is green."
        ),
    ),
    (
        "0",
        "0.2",
        "VERIFY",
        "Verify the standard is met",
        "All (A–S)",
        "When you want a read-only proof the standard is currently "
        "satisfied — no code changes.",
        "The exact headline reporting block from STANDARD.md §3 "
        "(no narrative, no editorialization).",
        (
            "Run npm run qa:gate (or the project's equivalent) plus "
            "npm run qa:live-stack:full and report the headline block "
            "exactly as defined in STANDARD.md §3 — no narrative, no "
            "editorialization, just the block. If any pillar A–S is "
            "Not Run, list it explicitly."
        ),
    ),
    (
        "1",
        "1.1",
        "APPLY",
        "Add functional smoke for <route> (Pillar A)",
        "A — Functional smoke",
        "New route, new role, new flow that needs first-line happy / "
        "negative path coverage.",
        "A new spec at tests/e2e/A-functional-smoke/<slug>.spec.ts "
        "with positive + negative paths, real CSRF auth, per-screen "
        "and per-flow cards updated.",
        (
            "Add a Pillar A spec covering <route, e.g. "
            "/providers/[id]/edit> for the <role, e.g. Provider | "
            "Operations | Committee | RCM/Billing | Admin> role. "
            "The spec must:\n"
            "- Live at tests/e2e/A-functional-smoke/<slug>.spec.ts.\n"
            "- Authenticate via the real CSRF sign-in helper, never "
            "a mocked session.\n"
            "- Assert at least one positive path AND one negative "
            "path (auth redirect, 403, validation failure).\n"
            "- Be added to the route's per-screen card under "
            "docs/qa/per-screen/<slug>.md (Linked specs: field).\n"
            "- Be added to the relevant per-flow card under "
            "docs/qa/per-flow/<slug>.md if the route is part of a "
            "multi-step flow.\n"
            "Then run npm run test:e2e -- A-functional-smoke and "
            "paste the full headline reporting block. Do not mark "
            "Done. until the coverage gate "
            "(npm run qa:check-coverage) is also green."
        ),
    ),
    (
        "1",
        "1.2",
        "APPLY",
        "Add role-by-role auth coverage matrix entry (Pillar B)",
        "B — RBAC",
        "New route that needs explicit per-role expected status "
        "(200 / 302→/login / 403).",
        "Updated tests/e2e/B-rbac/role-matrix.spec.ts with the new "
        "row, expected statuses sourced from "
        "docs/qa/policies/role-matrix.md.",
        (
            "Extend the Pillar B role-matrix spec at "
            "tests/e2e/B-rbac/role-matrix.spec.ts to cover <route>. "
            "For each of the five roles (Provider, Operations, "
            "Committee, RCM/Billing, Admin), assert the expected "
            "status (200, 302→/login, 403). The expected matrix MUST "
            "come from docs/qa/policies/role-matrix.md; if the "
            "policy is silent on this route, edit the policy first "
            "(and cite ADR or a stakeholder decision) before writing "
            "the spec. Run npm run test:e2e -- B-rbac and paste the "
            "headline block."
        ),
    ),
    (
        "1",
        "1.3",
        "APPLY",
        "Add accessibility coverage for <route> (Pillar E)",
        "E — Accessibility (axe-core)",
        "New screen, redesign, or any route that has not been "
        "accessibility-tested.",
        "A new spec at tests/e2e/E-accessibility/<slug>.spec.ts "
        "asserting zero serious/critical axe violations + landmark + "
        "heading + accessible-name checks.",
        (
            "Add a Pillar E axe-core spec at "
            "tests/e2e/E-accessibility/<slug>.spec.ts for <route> "
            "that:\n"
            "- Loads the page in the authenticated state for the "
            "role normally on this surface.\n"
            "- Runs axe.run() and asserts zero serious and zero "
            "critical violations.\n"
            "- Asserts the route has exactly one <main> landmark, "
            "at least one <h1>, and that every interactive control "
            "has an accessible name (aria-label, aria-labelledby, or "
            "visible label association).\n"
            "- Captures the axe report as a CI artifact under "
            "playwright-report-pillar-e/.\n"
            "Run npm run test:e2e -- E-accessibility and paste the "
            "headline block. The hard-fail rule is unconditional — "
            "serious/critical = 0, no exceptions."
        ),
    ),
    (
        "1",
        "1.4",
        "APPLY",
        "Add API contract coverage for <endpoint> (Pillar J)",
        "J — API contract (OpenAPI 3.1 / RFC 9457)",
        "New REST endpoint, tRPC procedure, or any change to a "
        "response shape.",
        "A new spec at tests/e2e/J-api-contract/<slug>.spec.ts "
        "validating live response against docs/api/openapi-v1.yaml + "
        "RFC 9457 problem+json on errors + "
        "route-inventory.json group registration.",
        (
            "Add a Pillar J contract spec at "
            "tests/e2e/J-api-contract/<slug>.spec.ts that:\n"
            "- Hits <endpoint> against the live dev stack with the "
            "role's real CSRF session.\n"
            "- Asserts the response shape against the OpenAPI 3.1 "
            "spec at docs/api/openapi-v1.yaml.\n"
            "- Verifies the application/problem+json shape on every "
            "error path per RFC 9457.\n"
            "- Confirms the endpoint is registered in "
            "route-inventory.json with the correct group: "
            "(public | authenticated | admin).\n"
            "If the OpenAPI spec disagrees with the response, that "
            "is a contract drift hard-fail (§4 condition 8) — fix "
            "the API or the spec, do not weaken the assertion. Run "
            "npm run test:e2e -- J-api-contract and paste the "
            "headline block."
        ),
    ),
    (
        "1",
        "1.5",
        "APPLY",
        "Add Pillar S live-stack probe for <surface>",
        "S — Live-stack reality (surfaces 1–7)",
        "New deploy-affecting change (auth, middleware, Prisma, "
        "Dockerfile, compose, env, public artifact, dev compiler).",
        "A new probe in scripts/qa/live-stack-smoke.mjs in the right "
        "surface bucket, hitting the deployed running stack with a "
        "deterministic invariant.",
        (
            "Extend scripts/qa/live-stack-smoke.mjs to add a probe "
            "for <surface>. Choose the right surface bucket (1 "
            "bring-up, 2 migrations, 3 sign-in matrix, 4 "
            "authenticated session, 5 anonymous public, 6 "
            "named-volume, 7 dev-perf). The probe MUST:\n"
            "- Hit the deployed running stack on localhost:<port>, "
            "not a mock.\n"
            "- Time out at 90 seconds and report NOTRUN (not FAIL) "
            "if Docker itself is unreachable.\n"
            "- Compare against a deterministic invariant — never a "
            "'looks reasonable' assertion.\n"
            "Run npm run qa:live-stack:full and paste the headline "
            "block, including the Live stack: <SHA> | "
            "migrations: … line."
        ),
    ),
    (
        "1",
        "1.6",
        "VERIFY",
        "Show me everything we have for Pillar <X>",
        "Any of A–S",
        "Pillar audit — read-only inventory of specs, screens, "
        "flows, and last-run results for one pillar.",
        "A markdown table with columns Spec | Linked screens | "
        "Linked flows | Last result | Last duration. No new tests "
        "run.",
        (
            "List every spec under tests/e2e/<X>-*/, every "
            "per-screen card that links to it, every per-flow card "
            "that links to it, and the latest run results from CI. "
            "Do not run new tests. Output as a markdown table with "
            "columns: Spec | Linked screens | Linked flows | Last "
            "result | Last duration."
        ),
    ),
    (
        "2",
        "2.1",
        "APPLY",
        "Update all documentation to reflect <change>",
        "Q — Documentation integrity",
        "After any change that ships and affects more than one "
        "required doc.",
        "A sweep across every required doc (system-prompt, BRD, "
        "FRD, TRD, architecture, definition-of-done, stakeholder "
        "brief, ADR README, CLAUDE.md, AGENTS.md, README.md, PR "
        "template, CHANGELOG, per-screen and per-flow cards), with "
        "anti-weakening on historical version refs, plus green "
        "forbidden-terms and linkcheck.",
        (
            "Update every required document affected by <change>. "
            "Required documents are listed in docs/README.md under "
            "'Quick navigation' and include at minimum: "
            "docs/system-prompt.md, docs/development-plan.md, "
            "docs/technical/technical-requirements.md, "
            "docs/technical/architecture.md, "
            "docs/business/business-requirements.md, "
            "docs/functional/functional-requirements.md, "
            "docs/qa/STANDARD.md (only if the standard itself "
            "changed), docs/qa/definition-of-done.md, "
            "docs/qa/README.md, docs/product/stakeholder-brief.md, "
            "docs/dev/adr/README.md and a new ADR if the change is "
            "architectural, CLAUDE.md, AGENTS.md, root README.md, "
            ".github/pull_request_template.md, and the CHANGELOG.md.\n"
            "\n"
            "Also update any per-screen card under "
            "docs/qa/per-screen/ and per-flow card under "
            "docs/qa/per-flow/ whose surface this change touches.\n"
            "\n"
            "Anti-weakening: do NOT collapse historical version "
            "references in the changelog or in old phase "
            "descriptions. v1.2.0 in a 2026-04-18 phase row is a "
            "fact; the doc-update sweep replaces it with v1.3.0 "
            "only where the row describes the *current* state.\n"
            "\n"
            "Run node scripts/forbidden-terms.mjs and "
            "npm run linkcheck after the sweep; both must be green. "
            "Then output the headline block."
        ),
    ),
    (
        "2",
        "2.2",
        "APPLY",
        "Open an ADR for <decision>",
        "Q — Documentation integrity",
        "After any architectural decision (new pattern, retired "
        "pattern, new constraint, new gate).",
        "A new docs/dev/adr/####-<slug>.md covering context, "
        "decision (with anti-weakening bullets), alternatives, "
        "consequences, validation evidence; ADR README updated.",
        (
            "Open a new ADR under docs/dev/adr/ using the next free "
            "number (look at the index in docs/dev/adr/README.md). "
            "The ADR MUST cover:\n"
            "- Context (the trigger, including any DEF-#### that "
            "exposed it).\n"
            "- Decision (the binding rule going forward, with "
            "anti-weakening bullets).\n"
            "- Alternatives considered, with reasons rejected.\n"
            "- Consequences (positive and negative).\n"
            "- Validation evidence (real numbers from the live "
            "stack).\n"
            "Then update docs/dev/adr/README.md to include the new "
            "ADR and output the headline block."
        ),
    ),
    (
        "2",
        "2.3",
        "VERIFY",
        "Audit documentation drift for <area>",
        "Q — Documentation integrity",
        "Before a release; before a customer demo; periodic "
        "doc-hygiene sweep.",
        "A markdown table of drift rows in path:line — claim vs. "
        "reality format. No fixes.",
        (
            "Compare every required doc that touches <area> against "
            "the current code. List every drift you find with "
            "path:line — claim vs. reality rows. Do not fix "
            "anything; this is a read-only audit. Output as a "
            "markdown table."
        ),
    ),
    (
        "3",
        "3.1",
        "APPLY",
        "Audit and fix UI/UX for <route or component>",
        "E + F + G — Accessibility, visual, responsive",
        "New screen, redesign, accessibility audit, mobile / tablet "
        "bug, design-token violation.",
        "Per-issue fixes for contrast, landmarks, headings, "
        "accessible names, focus rings, inline validation, async "
        "states, mobile/tablet layouts, raw-color removal; "
        "per-screen card updated; E + F + G suites run.",
        (
            "Audit <route or component> against the HDPulseAI UI/UX "
            "standard in docs/technical/architecture.md §'Design "
            "system' and the Pillar E hard-fail rules. "
            "Specifically:\n"
            "- WCAG 2.1 AA color contrast on every text + "
            "interactive element.\n"
            "- Single <main> landmark, exactly one <h1>, semantic "
            "heading order with no skipped levels.\n"
            "- Every interactive control has an accessible name "
            "AND a visible focus ring.\n"
            "- Forms have inline validation messages (not just "
            "toast); errors carry aria-describedby.\n"
            "- All async operations show a loading state and an "
            "error state in addition to the success state.\n"
            "- Mobile (375 wide) and tablet (768 wide) layouts are "
            "not broken (Pillar G).\n"
            "- No hard-coded raw color hex outside the design "
            "tokens (the no-raw-color ESLint rule).\n"
            "\n"
            "Fix every issue you find. For each fix, update or add "
            "the relevant per-screen card under "
            "docs/qa/per-screen/<slug>.md. Then run npm run "
            "test:e2e -- E-accessibility F-visual G-cross-browser "
            "and paste the headline block."
        ),
    ),
    (
        "3",
        "3.2",
        "APPLY",
        "Add visual regression baseline for <route> (Pillar F)",
        "F — Visual regression",
        "New screen; redesigned screen; first time covering an "
        "existing screen with snapshots.",
        "A new tests/e2e/F-visual/<slug>.spec.ts with seeded "
        "Chromium/Firefox/WebKit snapshots at 375/768/1440, "
        "committed baselines, second-run pass.",
        (
            "Add a Pillar F visual regression spec at "
            "tests/e2e/F-visual/<slug>.spec.ts that snapshots "
            "<route> in Chromium, Firefox, and WebKit at the three "
            "default viewports (375, 768, 1440). Update the "
            "per-screen card to link the new spec. Run npm run "
            "test:e2e -- F-visual --update-snapshots ONCE to seed "
            "baselines, commit the baseline images, then re-run "
            "npm run test:e2e -- F-visual (without "
            "--update-snapshots) to confirm it passes against "
            "itself. Paste both headline blocks."
        ),
    ),
    (
        "3",
        "3.3",
        "VERIFY",
        "Show me the UI/UX gaps on <route>",
        "E + F",
        "Pre-redesign audit; pre-launch accessibility check; "
        "stakeholder review prep.",
        "A markdown gap table: Issue | Severity (axe) | Viewport | "
        "WCAG criterion | Fix hint. No fixes.",
        (
            "Open <route> in the live dev stack, run axe-core, "
            "capture screenshots at the three default viewports, "
            "and report every Pillar E or F issue. Do not fix "
            "anything. Output as a markdown table: Issue | Severity "
            "(axe) | Viewport | WCAG criterion | Fix hint."
        ),
    ),
    (
        "4",
        "4.1",
        "APPLY",
        "Bring up the dev stack and verify Pillar S green",
        "S — Live-stack reality",
        "Local stack bring-up; pre-deploy gate; post-pull sanity "
        "check; daily standup green-light.",
        "docker compose up + qa:live-stack:full + the headline "
        "block + the per-surface PASS/FAIL/NOTRUN table; defect "
        "card opened on any FAIL.",
        (
            "Run docker compose -f docker-compose.dev.yml up -d, "
            "wait for healthy, then run npm run qa:live-stack:full. "
            "Paste the full headline block including Live stack: "
            "<SHA> | migrations: N pending | sign-in matrix: … and "
            "the per-surface PASS/FAIL/NOTRUN table. If any surface "
            "is FAIL, open a defect card per STANDARD.md §4.1 and "
            "start the Fix-Until-Green loop (cap N=3)."
        ),
    ),
    (
        "4",
        "4.2",
        "APPLY",
        "Diagnose and fix slow dev-loop compile (Surface 7)",
        "S — Live-stack reality (Surface 7, dev-perf)",
        "Slow page navigation in dev; compile times exceeding "
        "2000 ms; DEF-0014-style regression.",
        "Root-cause fix to package.json#scripts.dev / warmer / "
        "next.config.mjs / route handler — never raise the budget; "
        "qa:live-stack:full --dev-perf green; dev-perf p95 line in "
        "the headline.",
        (
            "Run npm run dev:warm against the live dev stack. "
            "Capture the per-route compile times from the warmer "
            "log. If any cold compile exceeds 2000 ms OR any "
            "re-fetch (warmed) compile exceeds 2000 ms, diagnose "
            "the root cause from these candidates:\n"
            "1. Compiler regressed off Turbopack (check "
            "package.json#scripts.dev).\n"
            "2. Dynamic-route warmer skipped a route family (check "
            "scripts/dev/warm-routes.mjs and route-inventory.json).\n"
            "3. onDemandEntries cache evicted before re-fetch "
            "(check next.config.mjs).\n"
            "4. A route's data layer regressed (check the route "
            "handler).\n"
            "Fix the root cause, NOT the budget. Re-run npm run "
            "qa:live-stack:full --dev-perf and paste the headline "
            "block. The dev-perf p95 line is required."
        ),
    ),
    (
        "4",
        "4.3",
        "VERIFY",
        "Show me the dev-loop performance numbers",
        "S — Live-stack reality (Surface 7, dev-perf)",
        "Read-only check that dev-perf budget is being met across "
        "all warmed routes.",
        "Per-route table: route | compile ms | re-fetch ms | budget "
        "ms | status; rows >80% of budget flagged WATCH.",
        (
            "Run npm run qa:live-stack:perf (or npm run "
            "qa:live-stack:full --dev-perf for the full surface "
            "set). Output the per-route table: route | compile ms "
            "| re-fetch ms | budget ms | status. Highlight any row "
            "that exceeds 80% of the budget as WATCH."
        ),
    ),
    (
        "5",
        "5.1",
        "APPLY",
        "Run security scan and fix critical findings (Pillar I)",
        "I — Security",
        "Quarterly security review; pre-launch security gate; new "
        "auth or data surface.",
        "DAST run + per-surface fixes for every Critical/High "
        "finding (no suppressions); per-screen card updated with "
        "control reference; defect cards for >1-PR fixes.",
        (
            "Run npm run security:dast -- --target <surface> (or "
            "the project's ZAP/Burp equivalent). For every Critical "
            "or High finding, fix the underlying issue — never "
            "suppress. Update the per-screen card with the security "
            "control reference. Open a defect card with Pillar: I "
            "for any finding that takes more than one PR to close. "
            "Run npm run test:e2e -- I-security and paste the "
            "headline block."
        ),
    ),
    (
        "5",
        "5.2",
        "APPLY",
        "Add HIPAA / NCQA / CMS-0057-F / JC compliance tag (Pillar P)",
        "P — Compliance",
        "Spec covers a control mapped to HIPAA / NCQA / CMS-0057-F "
        "/ Joint-Commission; audit prep.",
        "A spec annotated with @hipaa / @ncqa / @cms-0057-f / "
        "@jc-npg-12; docs/compliance/control-mapping.md updated; "
        "P-compliance suite green.",
        (
            "Tag <spec> with the relevant compliance annotations "
            "(@hipaa, @ncqa, @cms-0057-f, @jc-npg-12) per "
            "docs/compliance/. The annotation is binding: "
            "regression of a tagged spec is a §4 condition-9 "
            "hard-fail. Update docs/compliance/control-mapping.md "
            "to link the tag to the control it satisfies. Run "
            "npm run test:e2e -- P-compliance and paste the "
            "headline block."
        ),
    ),
    (
        "6",
        "6.1",
        "APPLY",
        "Open a defect card for <failure>",
        "Whatever pillar surfaced the failure",
        "When something breaks in CI, in dev, or in prod.",
        "A new docs/qa/defects/DEF-####.md filled per _TEMPLATE.md "
        "(metadata, evidence, hard-fails tripped, root cause, "
        "Fix-Until-Green attempts ≤ 3); index updated; not closed "
        "until §4.2 attestation is filled.",
        (
            "Open the next free defect card under "
            "docs/qa/defects/DEF-####.md (look at the index for the "
            "next number). Use _TEMPLATE.md. Fill in:\n"
            "- Metadata (severity, pillar, affected routes, "
            "affected roles, browser, failing spec).\n"
            "- Captured evidence (verbatim console error, "
            "trace.zip, screenshot, network HAR for any 5xx).\n"
            "- Hard-fail conditions tripped (check the boxes in "
            "the template).\n"
            "- Root-cause analysis (what was actually broken, not "
            "just the symptom).\n"
            "- Fix-Until-Green attempts (cap N=3).\n"
            "\n"
            "Add the new card to docs/qa/defects/index.md. Do not "
            "mark Closed (fixed) until the §4.2 anti-weakening "
            "attestation is filled in."
        ),
    ),
    (
        "6",
        "6.2",
        "APPLY",
        "Close DEF-####",
        "Whatever pillar the defect lives in",
        "When a fix is ready to land and all anti-weakening boxes "
        "can be honestly checked.",
        "DEF-#### card filled with §4.2 attestation, fix commit "
        "SHA, pillar(s) green again, forward-looking hardening; "
        "index flipped to **Closed (fixed)**; gate headline block.",
        (
            "Close DEF-#### per STANDARD.md §4.2. The card MUST "
            "contain:\n"
            "- Anti-weakening attestation with every box checked "
            "appropriately (no .skip, no .todo, no "
            "@ts-expect-error, no widening selectors, no swallowed "
            "errors, no raised timeouts, no lowered coverage "
            "thresholds, no edits to scripts/qa/check-coverage.ts "
            "or any inventory to silence).\n"
            "- The fix commit SHA.\n"
            "- The pillar(s) green again.\n"
            "- Any 'forward-looking hardening' follow-ups.\n"
            "Update docs/qa/defects/index.md to flip the status to "
            "**Closed (fixed)**. Output the headline block from "
            "the gate that closed it."
        ),
    ),
    (
        "7",
        "7.1",
        "APPLY",
        "Push, commit, and deploy",
        "All (A–S)",
        "Shipping a change to production.",
        "Local gates green → staged change → conventional commit → "
        "push → deploy.py run → /api/health 200 → container "
        "ps healthy.",
        (
            "1. Run npm run qa:gate AND npm run qa:live-stack:full "
            "against the local dev stack. Both must be green.\n"
            "2. Stage every file you intend to ship (git add -A), "
            "confirm git status --short matches the change you "
            "mean to commit.\n"
            "3. Write a commit message in the HDPulseAI "
            "Conventional Commit format: <type>(<scope>): "
            "<imperative summary> on line 1, then a body covering "
            "symptom, root cause, fix-and-why, verification "
            "numbers, anti-weakening attestation (§4.2), "
            "defect-ledger update (if any).\n"
            "4. Commit with git commit -F .git/COMMIT_MSG.tmp (or "
            "-m for short messages). NEVER use --amend on a pushed "
            "commit.\n"
            "5. git push origin master.\n"
            "6. $env:ALLOW_DEPLOY = '1'; python .claude/deploy.py.\n"
            "7. After the deploy, hit /api/health and assert 200. "
            "Output the deploy log tail and the post-deploy "
            "container ps with health status.\n"
            "\n"
            "If the deploy fails at the build step, treat it as a "
            "§4 hard-fail: open the next free defect card, fix the "
            "root cause, commit + push the fix, re-deploy. Do not "
            "retry-deploy without a code change."
        ),
    ),
    (
        "7",
        "7.2",
        "VERIFY",
        "Confirm production is healthy",
        "S — Live-stack reality",
        "Post-deploy verification; on-call check; status page "
        "confirmation.",
        "Container health status from docker compose ps + the "
        "/api/health HTTP code. No code changes.",
        (
            "Run python .claude/deploy.py 'cd /var/www/<repo> && "
            "docker compose -f docker-compose.prod.yml ps && "
            "curl -sS -o /dev/null -w \\'%{http_code}\\' "
            "http://localhost:<port>/api/health'. Report container "
            "health status and the HTTP code. No code changes."
        ),
    ),
    (
        "8",
        "8.1",
        "APPLY",
        "Bootstrap a new repo with the HDPulseAI standard",
        "Q — Documentation integrity (and propagation)",
        "Onboarding a new repo, or an existing repo that was never "
        "wired into the standards.",
        "L2 forwarders dropped (Cursor + GitHub Copilot + AGENTS + "
        "CLAUDE + .vscode/settings.json); audit row for the new "
        "repo pasted as proof.",
        (
            "Run node <path-to-E_Credentialing>/scripts/standards/"
            "bootstrap-repo.mjs <absolute-path-to-this-new-repo> "
            "from any shell. This drops the per-repo forwarders for "
            "Cursor, GitHub Copilot, Claude Code, AGENTS.md, and "
            ".vscode/settings.json. Confirm by running node "
            "<path-to-E_Credentialing>/scripts/standards/"
            "audit-propagation.mjs and pasting the row for the new "
            "repo."
        ),
    ),
    (
        "8",
        "8.2",
        "APPLY",
        "Re-bootstrap every HDPulseAI repo on this machine",
        "Q — Documentation integrity (and propagation)",
        "After a STANDARD.md version bump; after a new HDPulseAI "
        "repo appears on disk; periodic refresh.",
        "All 16 repos re-bootstrapped + VSCode user setup refreshed "
        "+ updated audit table pasted; commits inside the canonical "
        "repo only.",
        (
            "Run node scripts/standards/bootstrap-repo.mjs --all "
            "from the E_Credentialing repo. Then run node "
            "scripts/standards/bootstrap-vscode-user.mjs. Then "
            "re-run node scripts/standards/audit-propagation.mjs "
            "and paste the updated table. Commit any changes "
            "inside the canonical repo only; per-repo forwarders "
            "in sibling repos are local opt-ins."
        ),
    ),
    (
        "8",
        "8.3",
        "VERIFY",
        "Audit propagation across all repos",
        "Q — Documentation integrity (and propagation)",
        "After a clone on a new machine; after onboarding a new "
        "repo; periodic check.",
        "The full audit table from audit-propagation.mjs; any RED "
        "row gets a one-line bootstrap remediation suggested.",
        (
            "Run node scripts/standards/audit-propagation.mjs. "
            "Paste the table verbatim. For every repo where the "
            "standard does not resolve (no L1 in-repo, no L2 "
            "forwarders, no L3/L4 reachable), flag it as RED and "
            "propose a one-line bootstrap remediation."
        ),
    ),
    (
        "9",
        "9",
        "APPLY",
        "Kitchen-sink (all-in-one walk-away)",
        "All (A–S)",
        "Long-running tasks where you want a single instruction "
        "that covers the entire standard cycle and you plan to walk "
        "away for hours.",
        "11-step cycle from STANDARD read → plan → implement → "
        "test → fix-until-green → docs → commit → push → deploy "
        "(if requested) → headline block + Done.",
        (
            "Apply the HDPulseAI QA Standard to the following work: "
            "<your task>.\n"
            "\n"
            "Do all of:\n"
            "1. Read docs/qa/STANDARD.md (or "
            "~/.cursor/rules/qa-standard-global.mdc if absent).\n"
            "2. Read every doc the change might touch "
            "(docs/system-prompt.md, docs/development-plan.md, "
            "docs/technical/*.md, docs/qa/per-screen/*.md, "
            "docs/qa/per-flow/*.md, docs/dev/adr/*.md).\n"
            "3. Make a TodoWrite list of every concrete sub-task "
            "before you start writing code.\n"
            "4. Implement the change, satisfying every relevant "
            "pillar A–S.\n"
            "5. Add or update at least one spec per pillar touched, "
            "plus the per-screen and per-flow cards.\n"
            "6. Run npm run typecheck, npm run lint, "
            "npm run test:e2e, npm run qa:gate, and "
            "npm run qa:live-stack:full. Every gate must end at "
            "exit 0.\n"
            "7. If anything fails, open a defect card per "
            "STANDARD.md §4.1 and run the Fix-Until-Green loop "
            "(cap N=3). Do not weaken assertions, do not skip "
            "tests, do not raise timeouts.\n"
            "8. Update every affected required doc.\n"
            "9. Commit in the HDPulseAI Conventional Commit format "
            "with the full body (symptom, root cause, fix-and-why, "
            "verification numbers, anti-weakening attestation, "
            "defect updates).\n"
            "10. Push to master and (if deploy was requested) run "
            "$env:ALLOW_DEPLOY = '1'; python .claude/deploy.py.\n"
            "11. Output a single final summary that begins with "
            "the headline block from STANDARD.md §3 and ends with "
            "Done. (and ONLY if every gate is green and every "
            "required doc is current).\n"
            "\n"
            "Do not stop until step 11 is satisfied."
        ),
    ),
]

WORKFLOWS = [
    (
        "Ship a new feature end-to-end",
        "From design to production, with the standard fully "
        "honored at each step.",
        "0.1 → 1.1 → 1.2 → 1.3 → 1.4 → 3.1 → 2.1 → 4.1 → 7.1",
    ),
    (
        "Add coverage to an existing route",
        "When the route exists but coverage is missing.",
        "1.6 (audit) → 1.1 → 1.2 → 1.3 → 1.4 → 3.1 → 0.2 (verify)",
    ),
    (
        "Fix a bug that just broke production",
        "Triage → defect card → fix → close → ship.",
        "6.1 → 4.1 (reproduce) → fix → 6.2 → 7.1 → 7.2",
    ),
    (
        "Diagnose and fix slow dev-loop",
        "When clicking through pages takes seconds (DEF-0014 style).",
        "4.3 → 4.2 → 0.2",
    ),
    (
        "Update docs after a wave of changes",
        "Multi-day work has landed; docs need to catch up.",
        "2.3 (audit) → 2.1 → 2.2 (if architectural) → 0.2",
    ),
    (
        "Onboard a brand-new repo to the standards",
        "First-time setup of a fresh repo.",
        "8.1 → 8.3 → (optionally) 4.1 if the repo runs a stack",
    ),
    (
        "Refresh propagation after STANDARD.md bumps",
        "When the QA Standard version moves (e.g. v1.3.0 → v1.4.0).",
        "8.2 → 8.3",
    ),
    (
        "Run a UI/UX accessibility audit on a screen",
        "Pre-launch a11y check or stakeholder review prep.",
        "3.3 (audit) → 3.1 (fix) → 1.3 (lock-in coverage) → 3.2",
    ),
    (
        "Pre-release security + compliance gate",
        "Quarterly review or pre-launch sign-off.",
        "5.1 → 5.2 → 0.2",
    ),
    (
        "Long walk-away task",
        "Hand the agent everything and check back in a few hours.",
        "9",
    ),
]

# ---------------------------------------------------------------------------
# STYLES
# ---------------------------------------------------------------------------

# HDPulseAI brand-aligned palette (kept simple; Excel only renders ARGB).
HEADER_FILL = PatternFill("solid", fgColor="FF1F3A5F")  # deep navy
HEADER_FONT = Font(name="Calibri", bold=True, color="FFFFFFFF", size=11)
SECTION_FILL = PatternFill("solid", fgColor="FFE7EEF7")  # pale navy
APPLY_FILL = PatternFill("solid", fgColor="FFE6F4EA")  # soft green
VERIFY_FILL = PatternFill("solid", fgColor="FFE3F2FD")  # soft blue
ZEBRA_FILL = PatternFill("solid", fgColor="FFF6F8FA")
TITLE_FONT = Font(name="Calibri", bold=True, size=18, color="FF1F3A5F")
SUBTITLE_FONT = Font(name="Calibri", italic=True, size=11, color="FF374151")
BODY_FONT = Font(name="Calibri", size=11)
MONO_FONT = Font(name="Consolas", size=10)
THIN = Side(style="thin", color="FFCBD5E1")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)

WRAP_TOP = Alignment(horizontal="left", vertical="top", wrap_text=True)
WRAP_CENTER = Alignment(horizontal="center", vertical="top", wrap_text=True)
LEFT_TOP = Alignment(horizontal="left", vertical="top", wrap_text=False)


def apply_header(ws, row: int, headers: list[str]) -> None:
    for col_idx, value in enumerate(headers, start=1):
        cell = ws.cell(row=row, column=col_idx, value=value)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = WRAP_CENTER
        cell.border = BORDER


def autosize(ws, widths: dict[int, int]) -> None:
    for col, w in widths.items():
        ws.column_dimensions[get_column_letter(col)].width = w


# ---------------------------------------------------------------------------
# SHEET BUILDERS
# ---------------------------------------------------------------------------


def build_readme(ws) -> None:
    ws.title = "Read me"
    ws.sheet_view.showGridLines = False

    ws["A1"] = "HDPulseAI Standards — Prompt Library"
    ws["A1"].font = TITLE_FONT
    ws.merge_cells("A1:B1")

    ws["A2"] = (
        "Workbook regenerated by "
        "scripts/standards/build-prompt-workbook.py. "
        "Canonical prompt bodies live in docs/standards/PROMPTS.md. "
        "When PROMPTS.md changes, edit the PROMPTS list in the script "
        "and re-run."
    )
    ws["A2"].font = SUBTITLE_FONT
    ws["A2"].alignment = WRAP_TOP
    ws.merge_cells("A2:B2")
    ws.row_dimensions[2].height = 36

    rows = [
        ("", ""),
        (
            "What this workbook is for",
            "A categorized, classified, copy-paste-friendly catalog "
            "of every prompt you should issue to Cursor, VSCode + "
            "GitHub Copilot, Claude Code, or any other AI agent "
            "running inside an HDPulseAI repository. Every prompt "
            "below applies the HDPulseAI QA Standard automatically "
            "because the propagation layers (see "
            "docs/standards/README.md) make the standard binding on "
            "every agent invocation.",
        ),
        (
            "How the numbering works",
            "Prompts are organized into 10 sections (0–9). Inside "
            "each section, prompts are numbered <section>.<index> "
            "(for example, 1.3 means 'third prompt in section 1, "
            "the testing section'). Section 9 has only one prompt, "
            "so it is just '9'. Section 10 in the markdown file is "
            "footnotes, not prompts; it does not appear here.",
        ),
        (
            "What the Type column means",
            "APPLY = the agent does work AND must meet the "
            "standard's deliverables (headline reporting block, "
            "anti-weakening attestation, Done. line). VERIFY = the "
            "agent proves the standard is met without changing any "
            "code. Use VERIFY prompts to push back when an APPLY "
            "result looks wrong.",
        ),
        (
            "How to use a prompt",
            "Open the 'All prompts' sheet, filter to the section "
            "or pillar you care about, copy the cell in the "
            "'Prompt body' column, paste into your AI agent's chat "
            "window, replace every <bracketed-placeholder> with a "
            "concrete value (route, role, endpoint, surface, "
            "decision, etc.), then send. The agent will return work "
            "plus the headline reporting block.",
        ),
        (
            "How to choose which prompt to use",
            "Start on the 'Workflows' sheet — it lists common "
            "scenarios (ship a feature, fix a bug, run an a11y "
            "audit, onboard a repo, etc.) with the recommended "
            "prompt sequence. If your scenario is not listed, use "
            "0.1 as the default and let the standard's deliverables "
            "shape the result.",
        ),
        (
            "Color legend",
            "Type column: green = APPLY, blue = VERIFY. Section "
            "header rows on the 'All prompts' sheet are pale navy. "
            "Header rows are deep navy with white text.",
        ),
        (
            "Sheets in this workbook",
            "1) Read me — this page. 2) Sections — the 10 "
            "categories with descriptions. 3) All prompts — flat "
            "table of every prompt with full body. 4) Workflows — "
            "recommended prompt sequences for common scenarios.",
        ),
        (
            "When PROMPTS.md is the source of truth",
            "PROMPTS.md is the file the agent's propagation layers "
            "reference. The workbook is a developer-facing view "
            "regenerated from a small script. If a prompt changes "
            "in PROMPTS.md but not in the script, the workbook is "
            "stale; run python scripts/standards/build-prompt-"
            "workbook.py to refresh.",
        ),
    ]
    r = 3
    for label, value in rows:
        ws.cell(row=r, column=1, value=label).font = Font(
            name="Calibri", bold=True, size=11, color="FF1F3A5F"
        )
        ws.cell(row=r, column=1).alignment = LEFT_TOP
        ws.cell(row=r, column=2, value=value).font = BODY_FONT
        ws.cell(row=r, column=2).alignment = WRAP_TOP
        ws.row_dimensions[r].height = max(20, 14 * (1 + len(value) // 90))
        r += 1

    autosize(ws, {1: 36, 2: 110})
    ws.freeze_panes = "A4"


def build_sections(ws) -> None:
    ws.title = "Sections"
    ws.sheet_view.showGridLines = False

    headers = [
        "#",
        "Section name",
        "What it covers",
        "When to use it",
        "# prompts",
    ]
    apply_header(ws, 1, headers)
    ws.row_dimensions[1].height = 28

    for i, (sid, name, what, when, count) in enumerate(SECTIONS, start=2):
        ws.cell(row=i, column=1, value=sid).alignment = WRAP_CENTER
        ws.cell(row=i, column=2, value=name).alignment = WRAP_TOP
        ws.cell(row=i, column=3, value=what).alignment = WRAP_TOP
        ws.cell(row=i, column=4, value=when).alignment = WRAP_TOP
        ws.cell(row=i, column=5, value=count).alignment = WRAP_CENTER
        for col in range(1, 6):
            cell = ws.cell(row=i, column=col)
            cell.font = BODY_FONT
            cell.border = BORDER
            if i % 2 == 0:
                cell.fill = ZEBRA_FILL
        ws.cell(row=i, column=2).font = Font(
            name="Calibri", bold=True, size=11, color="FF1F3A5F"
        )
        # Approximate row height: headroom for the longest of "what"/"when".
        longest = max(len(what), len(when))
        ws.row_dimensions[i].height = max(40, 14 * (1 + longest // 60))

    autosize(ws, {1: 5, 2: 32, 3: 70, 4: 50, 5: 11})
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:E{1 + len(SECTIONS)}"


def build_all_prompts(ws) -> None:
    ws.title = "All prompts"
    ws.sheet_view.showGridLines = False

    headers = [
        "Section",
        "ID",
        "Type",
        "Title",
        "Pillar(s)",
        "When to use",
        "Desired outcome",
        "Prompt body (copy & paste)",
    ]
    apply_header(ws, 1, headers)
    ws.row_dimensions[1].height = 30

    for i, (
        sid,
        pid,
        ptype,
        title,
        pillars,
        when,
        outcome,
        body,
    ) in enumerate(PROMPTS, start=2):
        ws.cell(row=i, column=1, value=sid).alignment = WRAP_CENTER
        ws.cell(row=i, column=2, value=pid).alignment = WRAP_CENTER
        ws.cell(row=i, column=3, value=ptype).alignment = WRAP_CENTER
        ws.cell(row=i, column=4, value=title).alignment = WRAP_TOP
        ws.cell(row=i, column=5, value=pillars).alignment = WRAP_TOP
        ws.cell(row=i, column=6, value=when).alignment = WRAP_TOP
        ws.cell(row=i, column=7, value=outcome).alignment = WRAP_TOP
        body_cell = ws.cell(row=i, column=8, value=body)
        body_cell.alignment = WRAP_TOP
        body_cell.font = MONO_FONT

        for col in range(1, 9):
            cell = ws.cell(row=i, column=col)
            cell.border = BORDER
            if col != 8:
                cell.font = BODY_FONT
        # Title bold
        ws.cell(row=i, column=4).font = Font(
            name="Calibri", bold=True, size=11
        )
        # Type color
        type_fill = APPLY_FILL if ptype == "APPLY" else VERIFY_FILL
        ws.cell(row=i, column=3).fill = type_fill
        ws.cell(row=i, column=3).font = Font(
            name="Calibri", bold=True, size=11
        )

        # Approximate row height by body length (60 chars/line @ 14pt).
        line_count = max(
            6,
            (len(body) // 60) + body.count("\n") + 2,
            (len(outcome) // 50) + 2,
        )
        ws.row_dimensions[i].height = min(420, 14 * line_count)

    autosize(
        ws,
        {1: 7, 2: 7, 3: 9, 4: 36, 5: 26, 6: 36, 7: 50, 8: 80},
    )
    ws.freeze_panes = "D2"
    ws.auto_filter.ref = f"A1:H{1 + len(PROMPTS)}"


def build_workflows(ws) -> None:
    ws.title = "Workflows"
    ws.sheet_view.showGridLines = False

    headers = ["Scenario", "Description", "Recommended prompt sequence"]
    apply_header(ws, 1, headers)
    ws.row_dimensions[1].height = 30

    for i, (name, desc, seq) in enumerate(WORKFLOWS, start=2):
        ws.cell(row=i, column=1, value=name).font = Font(
            name="Calibri", bold=True, size=11, color="FF1F3A5F"
        )
        ws.cell(row=i, column=1).alignment = WRAP_TOP
        ws.cell(row=i, column=2, value=desc).alignment = WRAP_TOP
        ws.cell(row=i, column=2).font = BODY_FONT
        seq_cell = ws.cell(row=i, column=3, value=seq)
        seq_cell.alignment = WRAP_TOP
        seq_cell.font = MONO_FONT

        for col in range(1, 4):
            cell = ws.cell(row=i, column=col)
            cell.border = BORDER
            if i % 2 == 0:
                cell.fill = ZEBRA_FILL
        ws.row_dimensions[i].height = max(36, 14 * (1 + len(desc) // 80))

    autosize(ws, {1: 36, 2: 70, 3: 50})
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:C{1 + len(WORKFLOWS)}"


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------


def main() -> int:
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    wb = Workbook()
    build_readme(wb.active)
    build_sections(wb.create_sheet("Sections"))
    build_all_prompts(wb.create_sheet("All prompts"))
    build_workflows(wb.create_sheet("Workflows"))

    wb.save(OUT_PATH)
    print(f"Wrote {OUT_PATH}")
    print(
        f"  Sections: {len(SECTIONS)}  Prompts: {len(PROMPTS)}  "
        f"Workflows: {len(WORKFLOWS)}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
