/**
 * scripts/qa/build-trpc-inventory.ts
 *
 * Walks src/server/api/routers/*.ts and lists every exported tRPC procedure
 * along with whether it's a query / mutation / subscription. The contract
 * pillar (H) asserts that every procedure has a spec.
 *
 * Usage:  npx tsx scripts/qa/build-trpc-inventory.ts
 */

import fg from "fast-glob";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  INVENTORY_DIR,
  REPO_ROOT,
  ROUTERS_DIR,
  readText,
  type TrpcInventoryEntry,
} from "./lib";

// Matches the canonical t3/tRPC v11 router idiom:
//   procName: protectedProcedure.input(...).query(async (...) => ...)
//   procName: publicProcedure.mutation(({ input }) => ...)
// Captures: 1=procName, 2=builder chain (so we can sniff query/mutation/subscription).
const PROC_RE =
  /(\w+)\s*:\s*(?:public|protected|admin|staff|trpc|t)\w*Procedure([\s\S]*?)(?=,\s*\w+\s*:|\}\s*\)\s*[,;])/g;

function detectKind(chain: string): TrpcInventoryEntry["kind"] {
  if (/\.subscription\s*\(/.test(chain)) return "subscription";
  if (/\.mutation\s*\(/.test(chain)) return "mutation";
  return "query";
}

async function main(): Promise<void> {
  const files = await fg("*.ts", { cwd: ROUTERS_DIR, absolute: true });

  const entries: TrpcInventoryEntry[] = [];
  for (const file of files) {
    const src = await readText(file);
    const router = path.basename(file, ".ts");
    PROC_RE.lastIndex = 0;
    let m: RegExpExecArray | null;
    while ((m = PROC_RE.exec(src)) !== null) {
      const procedure = m[1]!;
      const chain = m[2] ?? "";
      // Skip helper exports that aren't procedures
      if (procedure === "router" || procedure === "createTRPCRouter") continue;
      entries.push({
        router,
        procedure,
        kind: detectKind(chain),
        file: path.relative(REPO_ROOT, file).replaceAll("\\", "/"),
      });
    }
  }

  entries.sort((a, b) =>
    a.router === b.router ? a.procedure.localeCompare(b.procedure) : a.router.localeCompare(b.router),
  );

  await mkdir(INVENTORY_DIR, { recursive: true });
  const out = path.join(INVENTORY_DIR, "trpc-inventory.md");

  const md: string[] = [
    "# tRPC Procedure Inventory",
    "",
    "Generated by `scripts/qa/build-trpc-inventory.ts`. Do not hand-edit.",
    "",
    `**Routers:** ${new Set(entries.map((e) => e.router)).size}`,
    `**Procedures:** ${entries.length}`,
    `**Generated at:** ${new Date().toISOString()}`,
    "",
    "| # | Router | Procedure | Kind | File |",
    "| --- | --- | --- | --- | --- |",
  ];
  entries.forEach((e, i) => {
    md.push(`| ${i + 1} | ${e.router} | \`${e.procedure}\` | ${e.kind} | \`${e.file}\` |`);
  });
  md.push("");

  await writeFile(out, md.join("\n"), "utf8");
  await writeFile(
    path.join(INVENTORY_DIR, "trpc-inventory.json"),
    JSON.stringify(entries, null, 2),
    "utf8",
  );

  console.log(`trpc-inventory: ${entries.length} procedures -> ${path.relative(REPO_ROOT, out)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
