/**
 * scripts/qa/build-link-inventory.ts
 *
 * Walks every .tsx under src/ and extracts every <Link href="..."> and
 * <a href="..."> target. The smoke pillar (A) uses this list to assert that
 * every internal link in the app resolves (no 404, no 5xx).
 *
 * Usage:  npx tsx scripts/qa/build-link-inventory.ts
 */

import fg from "fast-glob";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  INVENTORY_DIR,
  REPO_ROOT,
  readText,
  type LinkInventoryEntry,
} from "./lib";

const HREF_RE = /href\s*=\s*(?:"([^"]+)"|'([^']+)'|\{`([^`]+)`\})/g;
const COMPONENT_RE = /<\s*(?:Link|a)\b[^>]*href\s*=/g;

function isExternal(href: string): boolean {
  return /^(https?:|mailto:|tel:)/i.test(href);
}

async function main(): Promise<void> {
  const files = await fg("src/**/*.tsx", { cwd: REPO_ROOT, absolute: true, dot: false });

  const entries: LinkInventoryEntry[] = [];
  const seen = new Set<string>();

  for (const file of files) {
    const src = await readText(file);
    if (!COMPONENT_RE.test(src)) continue;
    COMPONENT_RE.lastIndex = 0;

    // For each matched <Link|a … href=…>, walk forward one href value.
    let m: RegExpExecArray | null;
    HREF_RE.lastIndex = 0;
    // We can't perfectly correlate componentRe and HREF_RE positions without
    // a parser, but the COMPONENT_RE filter ensures the file actually contains
    // such an element; collecting every href value in the file is acceptable
    // as the false-positive rate is dominated by data-href / aria-href which
    // are extremely rare in this codebase. The link smoke spec then re-walks
    // hrefs from the actual rendered DOM, so this inventory is for coverage
    // accounting, not for the runtime assertion.
    while ((m = HREF_RE.exec(src)) !== null) {
      const href = m[1] ?? m[2] ?? m[3] ?? "";
      if (!href) continue;
      if (href.startsWith("#")) continue;
      const key = `${href}::${file}`;
      if (seen.has(key)) continue;
      seen.add(key);
      entries.push({
        href,
        file: path.relative(REPO_ROOT, file).replaceAll("\\", "/"),
        external: isExternal(href),
      });
    }
  }

  entries.sort((a, b) => (a.href === b.href ? a.file.localeCompare(b.file) : a.href.localeCompare(b.href)));

  const internal = entries.filter((e) => !e.external);
  const uniqueInternalHrefs = new Set(internal.map((e) => e.href));

  await mkdir(INVENTORY_DIR, { recursive: true });
  const out = path.join(INVENTORY_DIR, "link-inventory.md");

  const md: string[] = [
    "# Link Inventory",
    "",
    "Generated by `scripts/qa/build-link-inventory.ts`. Do not hand-edit.",
    "",
    `**Total href occurrences:** ${entries.length}`,
    `**Unique internal hrefs:** ${uniqueInternalHrefs.size}`,
    `**External links (mailto / tel / http):** ${entries.length - internal.length}`,
    `**Generated at:** ${new Date().toISOString()}`,
    "",
    "| # | href | external | file |",
    "| --- | --- | --- | --- |",
  ];
  entries.forEach((e, i) => {
    md.push(`| ${i + 1} | \`${e.href}\` | ${e.external ? "yes" : "no"} | \`${e.file}\` |`);
  });
  md.push("");

  await writeFile(out, md.join("\n"), "utf8");
  await writeFile(
    path.join(INVENTORY_DIR, "link-inventory.json"),
    JSON.stringify(entries, null, 2),
    "utf8",
  );

  console.log(
    `link-inventory: ${entries.length} hrefs (${uniqueInternalHrefs.size} unique internal) -> ${path.relative(REPO_ROOT, out)}`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
