/**
 * scripts/qa/build-api-inventory.ts
 *
 * Walks src/app/api/** /route.ts and produces docs/qa/inventories/api-inventory.md.
 * Detects which HTTP methods each route exports so the contract pillar (H) can
 * cross-check that every (route, method) cell has a spec.
 *
 * Usage:  npx tsx scripts/qa/build-api-inventory.ts
 */

import fg from "fast-glob";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  APP_DIR,
  INVENTORY_DIR,
  REPO_ROOT,
  apiFileToRoute,
  detectExportedMethods,
  readText,
  type ApiInventoryEntry,
} from "./lib";

async function main(): Promise<void> {
  const files = await fg("api/**/route.ts", { cwd: APP_DIR, absolute: true, dot: false });

  const entries: ApiInventoryEntry[] = [];
  for (const file of files) {
    const src = await readText(file);
    const methods = detectExportedMethods(src);
    if (methods.length === 0) {
      // A route.ts that exports neither a verb nor a re-export is a broken
      // route — fail the build of the inventory rather than silently skip.
      console.error(
        `api-inventory: ${path.relative(REPO_ROOT, file)} exports no HTTP method`,
      );
      process.exitCode = 1;
      continue;
    }
    const route = apiFileToRoute(file);
    entries.push({
      route,
      file: path.relative(REPO_ROOT, file).replaceAll("\\", "/"),
      methods,
      dynamic: /\[[^\]]+\]/.test(route),
    });
  }

  entries.sort((a, b) => a.route.localeCompare(b.route));

  await mkdir(INVENTORY_DIR, { recursive: true });
  const out = path.join(INVENTORY_DIR, "api-inventory.md");

  const md: string[] = [
    "# API Inventory",
    "",
    "Generated by `scripts/qa/build-api-inventory.ts`. Do not hand-edit.",
    "",
    `**Total API routes:** ${entries.length}`,
    `**Total (route, method) cells:** ${entries.reduce((s, e) => s + e.methods.length, 0)}`,
    `**Generated at:** ${new Date().toISOString()}`,
    "",
    "| # | Route | Methods | Dynamic | File |",
    "| --- | --- | --- | --- | --- |",
  ];
  entries.forEach((e, i) => {
    md.push(
      `| ${i + 1} | \`${e.route}\` | ${e.methods.join(", ")} | ${e.dynamic ? "yes" : "no"} | \`${e.file}\` |`,
    );
  });
  md.push("");

  await writeFile(out, md.join("\n"), "utf8");
  await writeFile(
    path.join(INVENTORY_DIR, "api-inventory.json"),
    JSON.stringify(entries, null, 2),
    "utf8",
  );

  console.log(`api-inventory: ${entries.length} routes -> ${path.relative(REPO_ROOT, out)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
