/**
 * scripts/qa/build-route-inventory.ts
 *
 * Walks src/app/** /page.tsx and produces docs/qa/inventories/route-inventory.md
 * with one row per Next.js route. This file is the **denominator** for the §3
 * headline block "Routes covered: X of Y" in `docs/qa/STANDARD.md`.
 *
 * Usage:  npx tsx scripts/qa/build-route-inventory.ts
 */

import fg from "fast-glob";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  APP_DIR,
  INVENTORY_DIR,
  REPO_ROOT,
  pageFileToRoute,
  type RouteInventoryEntry,
} from "./lib";

async function main(): Promise<void> {
  const pages = await fg("**/page.tsx", { cwd: APP_DIR, absolute: true, dot: false });

  const entries: RouteInventoryEntry[] = pages.map((file) => {
    const route = pageFileToRoute(file);
    const rel = path.relative(REPO_ROOT, file).replaceAll("\\", "/");
    const groupMatch = /\(([^)]+)\)/.exec(rel);
    return {
      route,
      file: rel,
      dynamic: /\[[^\]]+\]/.test(route),
      group: groupMatch?.[1] ?? "public",
    };
  });

  entries.sort((a, b) => a.route.localeCompare(b.route));

  await mkdir(INVENTORY_DIR, { recursive: true });
  const out = path.join(INVENTORY_DIR, "route-inventory.md");

  const md: string[] = [
    "# Route Inventory",
    "",
    "Generated by `scripts/qa/build-route-inventory.ts`. Do not hand-edit.",
    "",
    `**Total routes:** ${entries.length}`,
    `**Generated at:** ${new Date().toISOString()}`,
    "",
    "| # | Route | Group | Dynamic | File |",
    "| --- | --- | --- | --- | --- |",
  ];
  entries.forEach((e, i) => {
    md.push(`| ${i + 1} | \`${e.route}\` | ${e.group} | ${e.dynamic ? "yes" : "no"} | \`${e.file}\` |`);
  });
  md.push("");

  await writeFile(out, md.join("\n"), "utf8");

  // Also emit a machine-readable JSON sibling so check-coverage.ts can read it
  // without re-walking the filesystem.
  const json = path.join(INVENTORY_DIR, "route-inventory.json");
  await writeFile(json, JSON.stringify(entries, null, 2), "utf8");

  console.log(`route-inventory: ${entries.length} routes -> ${path.relative(REPO_ROOT, out)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
