/**
 * scripts/qa/build-route-inventory.ts
 *
 * Walks src/app/** /page.tsx and produces docs/qa/inventories/route-inventory.md
 * with one row per Next.js route. This file is the **denominator** for the §3
 * headline block "Routes covered: X of Y" in `docs/qa/STANDARD.md`.
 *
 * Usage:  npx tsx scripts/qa/build-route-inventory.ts
 */

import fg from "fast-glob";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  APP_DIR,
  INVENTORY_DIR,
  REPO_ROOT,
  pageFileToRoute,
  type RouteInventoryEntry,
} from "./lib";
import { isPublicRoute, isProviderPortalRoute } from "../../src/lib/public-routes";

/**
 * Classify a route into a single inventory `group` label.
 *
 * Precedence (per ADR 0028, DEF-0008/0011):
 *   1. Explicit Next.js `(group)/` segment in the on-disk path wins —
 *      it expresses authorial intent (e.g. `(staff)/dashboard`,
 *      `(provider)/application`).
 *   2. Otherwise, the SAME predicate the middleware uses at runtime
 *      (`isPublicRoute` from `src/lib/public-routes.ts`) decides
 *      whether the route is public. Drift between middleware and
 *      inventory is structurally impossible because both sides
 *      import the same module.
 *   3. Otherwise, default to `staff` — the middleware's behaviour
 *      for any path not in the public allow-list is to redirect
 *      anonymous callers to `/auth/signin`, so `staff` is the
 *      truthful classification for the inventory.
 *
 * The OLD implementation defaulted ALL ungrouped pages to `public`,
 * which silently mis-classified `/settings/billing` and
 * `/settings/compliance` (DEF-0011) and any future page added
 * outside a route-group folder.
 */
function classifyGroup(route: string, relFile: string): string {
  const groupMatch = /\(([^)]+)\)/.exec(relFile);
  if (groupMatch) return groupMatch[1]!;
  if (isPublicRoute(route)) return "public";
  if (isProviderPortalRoute(route)) return "provider";
  return "staff";
}

async function main(): Promise<void> {
  const pages = await fg("**/page.tsx", { cwd: APP_DIR, absolute: true, dot: false });

  const entries: RouteInventoryEntry[] = pages.map((file) => {
    const route = pageFileToRoute(file);
    const rel = path.relative(REPO_ROOT, file).replaceAll("\\", "/");
    return {
      route,
      file: rel,
      dynamic: /\[[^\]]+\]/.test(route),
      group: classifyGroup(route, rel),
    };
  });

  entries.sort((a, b) => a.route.localeCompare(b.route));

  await mkdir(INVENTORY_DIR, { recursive: true });
  const out = path.join(INVENTORY_DIR, "route-inventory.md");

  const md: string[] = [
    "# Route Inventory",
    "",
    "Generated by `scripts/qa/build-route-inventory.ts`. Do not hand-edit.",
    "",
    `**Total routes:** ${entries.length}`,
    `**Generated at:** ${new Date().toISOString()}`,
    "",
    "| # | Route | Group | Dynamic | File |",
    "| --- | --- | --- | --- | --- |",
  ];
  entries.forEach((e, i) => {
    md.push(`| ${i + 1} | \`${e.route}\` | ${e.group} | ${e.dynamic ? "yes" : "no"} | \`${e.file}\` |`);
  });
  md.push("");

  await writeFile(out, md.join("\n"), "utf8");

  // Also emit a machine-readable JSON sibling so check-coverage.ts can read it
  // without re-walking the filesystem.
  const json = path.join(INVENTORY_DIR, "route-inventory.json");
  await writeFile(json, JSON.stringify(entries, null, 2), "utf8");

  console.log(`route-inventory: ${entries.length} routes -> ${path.relative(REPO_ROOT, out)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
