/**
 * Wave 5.4 — auditor-package builder.
 *
 * Pulls audit log, NCQA snapshots, provider/license counts, and SOC 2
 * control evidence from the database and assembles them into a single
 * .zip ready for the auditor's secure dropbox.
 *
 * Used by:
 *   - `npm run compliance:auditor-package` (CLI in scripts/compliance/)
 *   - `POST /api/compliance/auditor-package` (in-app one-click export)
 *
 * Anti-weakening (STANDARD.md §4.2):
 *   - The output zip MUST be byte-stable across runs (same period →
 *     same SHA-256). The manifest sorts artifacts; CSVs are written in
 *     deterministic order.
 *   - Do NOT include raw PHI columns. The CSV exports cover the
 *     audit + control surfaces only. Per-provider data goes through
 *     the existing `npm run compliance:report` PHI-aware path.
 */

import { createHash } from "node:crypto";
import JSZip from "jszip";
import { db } from "@/server/db";
import { withTenant } from "@/server/db/tenant-context";
import { verifyAuditChain } from "@/lib/audit";
import {
  type AuditorManifest,
  type AuditorManifestArtifact,
  renderManifest,
} from "./manifest";
import {
  renderAuditLogCsv,
  renderCoverSheet,
  renderNcqaSnapshotsCsv,
} from "./sections";
import {
  SOC2_CONTROLS,
  renderControlMarkdown,
  renderGapAnalysisMarkdown,
} from "./soc2-controls";

export interface BuildPackageInput {
  organizationId: string;
  /** Optional reporting window. */
  reportPeriod?: { from: Date; to: Date };
  /** Pin generation timestamp (mainly for tests / reproducibility). */
  generatedAt?: Date;
}

export interface BuildPackageResult {
  zipBytes: Uint8Array;
  manifest: AuditorManifest;
  zipDigestSha256: string;
}

const README_BODY = `# Auditor package

This zip is generated by E-Credentialing CVO Platform on demand. It
contains the SOC 2 Type I evidence pack plus the chained audit log
and NCQA compliance snapshots.

## Anti-weakening

- \`manifest.json\` lists every file with its SHA-256.
- Re-running with the same organization and period MUST produce the
  same SHA-256 set. If it doesn't, history has been mutated and you
  should investigate immediately.
- Audit log rows are immutable at the database layer (triggers block
  UPDATE / DELETE / TRUNCATE). The HMAC chain detects tampering after
  the fact.

## Files

- \`audit-log.csv\` — chained audit log entries.
- \`ncqa-snapshots.csv\` — quarterly NCQA compliance snapshots.
- \`controls/*.md\` — one file per SOC 2 control evidence record.
- \`gap-analysis.md\` — summary of implemented / partial / gap controls.
- \`README.md\` — this file.
`;

export async function buildAuditorPackage(input: BuildPackageInput): Promise<BuildPackageResult> {
  const generatedAt = input.generatedAt ?? new Date();

  // The auditor package operates inside an explicit tenant scope so
  // the existing tenant Prisma extension auto-filters every query
  // back to this org. NcqaComplianceSnapshot and License are not
  // tenant-scoped models in W5.1.a, so they read globally.
  const data = await withTenant({ organizationId: input.organizationId }, () =>
    fetchAuditorData(input),
  );

  const chain = await verifyAuditChain();

  const auditCsv = renderAuditLogCsv(data.auditRows);
  const ncqaCsv = renderNcqaSnapshotsCsv(data.snapshots);
  const cover = renderCoverSheet({
    organizationName: data.org.name,
    organizationId: data.org.id,
    generatedAtIso: generatedAt.toISOString(),
    reportPeriod: input.reportPeriod
      ? {
          fromIso: input.reportPeriod.from.toISOString(),
          toIso: input.reportPeriod.to.toISOString(),
        }
      : undefined,
    auditChainOk: chain.ok,
    auditChainNullHashes: chain.nullHashes,
    auditLogRows: data.auditRows.length,
    ncqaSnapshotCount: data.snapshots.length,
    providerCount: data.providerCount,
    licenseCount: data.licenseCount,
  });
  const gapAnalysis = renderGapAnalysisMarkdown();

  const zip = new JSZip();
  const artifacts: AuditorManifestArtifact[] = [];

  function add(path: string, body: string, description: string): void {
    const bytes = Buffer.from(body, "utf-8");
    zip.file(path, bytes, {
      // Pin the timestamp so the zip is byte-stable across runs with
      // the same logical inputs.
      date: generatedAt,
      createFolders: false,
    });
    artifacts.push({
      path,
      description,
      digestSha256: sha256Hex(bytes),
      bytes: bytes.byteLength,
    });
  }

  add("README.md", README_BODY, "Anti-weakening notes for downstream auditors.");
  add("cover.md", cover, "Human-readable summary of the package.");
  add("audit-log.csv", auditCsv, "Tamper-evident audit log rows for the period.");
  add("ncqa-snapshots.csv", ncqaCsv, "NCQA compliance snapshots (all history).");
  add("gap-analysis.md", gapAnalysis, "SOC 2 Type I gap analysis summary.");

  for (const c of SOC2_CONTROLS) {
    const path = `controls/${c.ref}-${c.status}.md`;
    add(path, renderControlMarkdown(c), `SOC 2 ${c.ref} — ${c.title}`);
  }

  const manifest: AuditorManifest = {
    generatedAt: generatedAt.toISOString(),
    packageFormatVersion: "1.0.0",
    organizationId: data.org.id,
    organizationName: data.org.name,
    reportPeriod: input.reportPeriod
      ? {
          fromIso: input.reportPeriod.from.toISOString(),
          toIso: input.reportPeriod.to.toISOString(),
        }
      : undefined,
    summary: {
      auditLogRows: data.auditRows.length,
      auditChainOk: chain.ok,
      auditChainNullHashes: chain.nullHashes,
      ncqaSnapshotCount: data.snapshots.length,
      providerCount: data.providerCount,
      licenseCount: data.licenseCount,
    },
    artifacts,
  };
  zip.file("manifest.json", renderManifest(manifest), {
    date: generatedAt,
    createFolders: false,
  });

  const zipBytes = await zip.generateAsync({
    type: "uint8array",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });

  return {
    zipBytes,
    manifest,
    zipDigestSha256: sha256Hex(Buffer.from(zipBytes)),
  };
}

function sha256Hex(buf: Buffer): string {
  return createHash("sha256").update(buf).digest("hex");
}

async function fetchAuditorData(input: BuildPackageInput) {
  const org = await db.organization.findUnique({
    where: { id: input.organizationId },
  });
  if (!org) throw new Error(`Organization not found: ${input.organizationId}`);

  const auditWhere = input.reportPeriod
    ? { timestamp: { gte: input.reportPeriod.from, lte: input.reportPeriod.to } }
    : undefined;

  const [auditRows, snapshots, providerCount, licenseCount] = await Promise.all([
    db.auditLog.findMany({
      where: auditWhere,
      orderBy: { sequence: "asc" },
      select: {
        id: true,
        sequence: true,
        timestamp: true,
        actorId: true,
        actorRole: true,
        action: true,
        entityType: true,
        entityId: true,
        providerId: true,
        previousHash: true,
        hash: true,
      },
    }),
    db.ncqaComplianceSnapshot.findMany({
      orderBy: { takenAt: "asc" },
      select: {
        id: true,
        takenAt: true,
        totalCriteria: true,
        compliantCount: true,
        partialCount: true,
        nonCompliantCount: true,
        notApplicableCount: true,
        overallScore: true,
      },
    }),
    db.provider.count(),
    // License is joined to Provider; we filter via the provider relation
    // since License is not yet a tenant-scoped model in W5.1.a.
    db.license.count({
      where: { provider: { organizationId: input.organizationId } },
    }),
  ]);

  return { org, auditRows, snapshots, providerCount, licenseCount };
}
