import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
    DATABASE_URL: z.string().url(),
    REDIS_HOST: z.string().default("localhost"),
    REDIS_PORT: z.coerce.number().default(6379),
    AZURE_AD_TENANT_ID: z.string().min(1),
    AZURE_AD_CLIENT_ID: z.string().min(1),
    NEXTAUTH_SECRET: z.string().min(1),
    NEXTAUTH_URL: z.string().url().optional(),
    AZURE_KEY_VAULT_URL: z.string().url().optional(),
    AZURE_BLOB_ACCOUNT_URL: z.string().url().optional(),
    AZURE_BLOB_CONTAINER: z.string().default("essen-credentialing"),
    AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT: z.string().url().optional(),
    AZURE_COMMUNICATION_SERVICES_ENDPOINT: z.string().url().optional(),
    SENDGRID_API_KEY: z.string().optional(),
    SENDGRID_FROM_EMAIL: z.string().email().default("cred_onboarding@essenmed.com"),
    ENCRYPTION_KEY: z.string().min(1),
    BULL_BOARD_PORT: z.coerce.number().default(6025),
    SAM_GOV_API_KEY: z.string().optional(),
  },
  client: {
    NEXT_PUBLIC_APP_URL: z.string().url().default("http://localhost:6015"),
  },
  runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    DATABASE_URL: process.env.DATABASE_URL,
    REDIS_HOST: process.env.REDIS_HOST,
    REDIS_PORT: process.env.REDIS_PORT,
    AZURE_AD_TENANT_ID: process.env.AZURE_AD_TENANT_ID,
    AZURE_AD_CLIENT_ID: process.env.AZURE_AD_CLIENT_ID,
    NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
    AZURE_KEY_VAULT_URL: process.env.AZURE_KEY_VAULT_URL,
    AZURE_BLOB_ACCOUNT_URL: process.env.AZURE_BLOB_ACCOUNT_URL,
    AZURE_BLOB_CONTAINER: process.env.AZURE_BLOB_CONTAINER,
    AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT: process.env.AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT,
    AZURE_COMMUNICATION_SERVICES_ENDPOINT: process.env.AZURE_COMMUNICATION_SERVICES_ENDPOINT,
    SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
    SENDGRID_FROM_EMAIL: process.env.SENDGRID_FROM_EMAIL,
    ENCRYPTION_KEY: process.env.ENCRYPTION_KEY,
    BULL_BOARD_PORT: process.env.BULL_BOARD_PORT,
    SAM_GOV_API_KEY: process.env.SAM_GOV_API_KEY,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
  emptyStringAsUndefined: true,
});
